### ISSUE TITLE
[setting] NestJS 초기 설정

### ISSUE THREAD

**Issue by sween2591** [CMI-OSS/cbnu-alrami#108]
## ✨ What?

NestJS 초기설정 입니다.

## 🛠 How?

공통  3번까지
1. ConfigModule 설정 env파일로 적용
2. CORS, Helmet, compression
3. DatabaseModule <- 목표 + cafeteria 모듈 Read기능
4. morgan+LoggerService+ConsoleLogger+winston
5. static-serve (public폴더)
6. UploadModule
------------
Next: 추후 토의 후 확정되면 해야하는 부분
1. response interceptor 일반 response 양식
2. 예외처리
3. Exception Filter 에러 response 양식
4. passport strategy (fcm토큰,  jwt토큰, 일반 로그인)
5. AuthGuard(4번에서 만든 항목 guard생성)

### ✅ 참고 사항

공유할 내용, 스크린샷 등을 넣어 주세요.

- 추가적인 공유가 필요한 사항은 Comment

**Comment by JeongHyeongKim** [comment]
빡세시면 저랑 나눠서 하실까요?

질문 : static file의 경우에는 aws s3 + cloud front등을 이용하는 것은 어떠한가요?

**Comment by sween2591** [comment]
@JeongHyeongKim 전 좋아요! AWS쪽은 실제로 해본 적은 없어서 이번 기회에 사용하면 좋을 것 같습니다.
여유 되시는 시간이 혹시 어떻게 되시나요? 전 새벽도 괜찮아요!
