### ISSUE TITLE
[setting] 충림이 전체 아키텍처 설계 및 개선에 대한 제안

### ISSUE THREAD

**Issue by JeongHyeongKim** [CMI-OSS/cbnu-alrami#112]
## ✨ What?

기존 충림이를 cloud base로 설계하고, 기존 보다 더 나은 설계가 있으면 이를 논리적으로 제안한다.

## 🛠 How?

초안 공유 후 이에 대한 pr을 통한 review

### ✅ 참고 사항

완성이 되면 PR을 통해 서술 및 공유할 예정.

**Comment by jaryapp** [comment]
@JeongHyeongKim 
클라우드 베이스라면 구체적으로 어떤거일까요? 혹시 참고할만한 레퍼런스가 있을까요?

**Comment by JeongHyeongKim** [comment]
일반 레거시를 사용하는 것이 아닌 최대한 클라우드 서비스를 이용하는 것을 기준으로 설계하는 것입니다!
예시는 아래와 같습니다.
https://www.google.com/search?q=aws+architecture&rlz=1C5CHFA_enKR931KR931&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjvgMe_j6_2AhU-klYBHQpfDt4Q_AUoAXoECAEQAw&biw=1920&bih=881&dpr=1#imgrc=nABJSeqsACI-xM

**Comment by JeongHyeongKim** [comment]
https://drive.google.com/file/d/1j4nnLfUY2drxRxU51YK4win5BXTMTRSg/view?usp=sharing

**Comment by nohgijin** [comment]
@CMI-OSS/cbnu_alrami_be 코멘트가 3월 이후 안써져있는데 이 이슈 닫아도 되나요 ?
