### ISSUE TITLE
[server] Article 생성, 목록 조회, 상세 조회 API

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#128]
## 📌 개요

Article 테이블과 관련된 API를 개발합니다. 

## 👩‍💻 기능 설명

- 보드별 게시글 목록 조회
- 보드별 게시물 작성
  - 생성 시 Image 객체와 연결 과정 필요
- 보드별 게시물 상세 조회 

### ✅ 참고 사항

Article 테이블 구조입니다.
<img width="168" alt="스크린샷 2022-03-20 오후 12 21 22" src="https://user-images.githubusercontent.com/38103085/159146626-ed2e02ef-ee99-42dc-a2c3-185862fe8f7f.png">

- 추가적인 공유가 필요한 사항은 Comment

**Comment by jaryapp** [comment]
@EunjiShin 우디 `author` 컬럼명 `authorId`로 바꿨는데 제가 ERD에 반영을 안했네용; 참고 부탁드려요 Admin의 id랑 FK입니당

**Comment by EunjiShin** [comment]
확인했습니다! 공유 감사합니다 :)

**Comment by EunjiShin** [comment]
@CMI-OSS/cbnu_alrami_be 
url 필드 추가되었습니다! 
- url varchar[255]
