### ISSUE TITLE
[Feature - DB] Place 스키마 개선안

### ISSUE THREAD

**Issue by JeongHyeongKim** [CMI-OSS/cbnu-alrami#129]
## 📌 개요
기존 Place table에 대한 한계점을 보완합니다.

category로 인해 난해해진 스키마를 보완함.

## 👩‍💻 기능 설명

Place Table => 공통정보가 담긴 테이블사용
이 테이블을 impl받아사용하는 방향으로 설계예정

### ✅ 참고 사항

To Be Updated

**Comment by JeongHyeongKim** [comment]
https://dbdiagram.io/d/623b43acbed6183873e6ef04

진행중

**Comment by JeongHyeongKim** [comment]
@jaryapp 
안1
위 DB diagram처럼 구조를 가짐.
요구조건 : 각 구별된 Place 별로 고유한 데이터가 있어야함.

안2
위 다이어그램에서 각 장소에 대한 타입을 placed의 컬럼에서 관리함.


개인적으로는 안1을 추천
이유
1. 테이블은 쪼개지지만, 기획이 변경되었을 때 Place 전체가 영향을 받지 않고 해당 테이블만 수정하여 반영이 가능함. 즉, 요구사항 반영이 쉬우며 열려있는 설계가 가능함.
2. 한 테이블에 몰려있지 않기 때문에 색인에 조금이나마 더 유리
3. 백엔드에서 Schema를 이용하여 인스턴스를 만들 수 있는데 명시적으로 이게 이런 객체다 라는게 더 돋보임. (물론 트렌젝션 관리 해야함.)

**Comment by jaryapp** [comment]
@JeongHyeongKim 
DB Diagram 확인했습니당~ 저도 안1이 좋은것 같아요!
`Building` -> `University` 로 바꾸면 어떨까 합니다

**Comment by JeongHyeongKim** [comment]
네 building은 가제였고, 그당시에 생각이 안니서..
적당한거면 다 괜찮을듯합니다.

**Comment by jaryapp** [comment]
@JeongHyeongKim 
`Cafeteria` 테이블에 식당별 아침, 점심, 저녁 운영시간을 저장할 수 있는 컬럼이 필요합니다!
ex) `breakfast_time`, `lunch_time`, `dinner_time`

그리고 혹시 `sector`의 용도가 무엇일까용?

**Comment by JeongHyeongKim** [comment]
제 개인의견이 담긴건데,

식당의 경우, 중문 / 정문 이런 별칭을 나타낼 수 있고

학교의 경우에는 사회과학대학 이런걸로 표기할 수 있겠죠

이런 용도로 제가 임의로 삽입하였습니다.

**Comment by jaryapp** [comment]
@JeongHyeongKim 
그렇군요 그런 경우라면 별칭이라기 보다는 카테고리에 가까운것 같습니다.
저는 `Place`를 카테고리화 할 수 있는 테이블이 있으면 좋을것 같습니다
```
PlaceCategory {
  id:Int,
  name:String
}
```

```
Place {
   ...
   categoryId:PlaceCategory.id
   ...
}
