### ISSUE TITLE
[Feature-DB]User 스키마 개선안

### ISSUE THREAD

**Issue by sween2591** [CMI-OSS/cbnu-alrami#133]
## 📌 개요

![image](https://user-images.githubusercontent.com/61648828/160248664-b871e0c8-99af-4717-a691-0b2f0ee3e2c7.png)
해당 스키마의 uuid컬럼이 int형인 것 보다 문자열인 게 더 맞는 것 같습니다.

## 👩‍💻 기능 설명

![image](https://user-images.githubusercontent.com/61648828/160248706-57614086-bd00-4c0f-ab73-e4065881a04f.png)

uuid는 mongoDB의 ObjectId처럼 위 스크린샷과 같이 특정 패턴으로 생성된 랜덤 문자열이라고 알고있습니다.
따라서 int가 아니라 varchar로 저장해야하는 게 맞는 것같은데 다들 어떻게 생각하시나요?

### ✅ 참고 사항

공유할 내용, 스크린샷 등을 넣어 주세요.

- 추가적인 공유가 필요한 사항은 Comment

**Comment by jaryapp** [comment]
uuid는 string이 맞습니다~
