### ISSUE TITLE
[논의] Mysql column naming convention

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#134]
Mysql column naming convention 룰을 정합니다

`snake_case` vs `camelCase`

@CMI-OSS/cbnu_alrami_be  의견주세용~

**Comment by EunjiShin** [comment]
저는 **snake_case**가 좋습니다. 
탁월한 성능상의 이점이 있다기보다는 개인적으로 익숙한 방법이고, 대부분의 레퍼런스에서 추천하는 방식이라 더 끌리는 것 같네요ㅎㅎ
StackOverflow에서는 **SQL에서 대소문자 구분이 안되는 이슈때문에 언더바를 사용하는 snake_case를 권장**한다는 의견도 있습니다. 
([출처](https://stackoverflow.com/questions/16288586/any-reason-to-still-use-snake-case-for-database-tables-and-columns))

하지만 슬랙에서 조나슨이 언급하셨던 [typeorm-naming-strategies](https://www.npmjs.com/package/typeorm-naming-strategies)를 이용해 자동으로 snake_case <-> camelCase 변환하는 건 반대입니다. 회의 때 말씀드린 것처럼, 저희 컨트롤을 벗어나게 된다는 점에서 우려가 되네요. 정해진 룰이 있다고 해도요!

만약 column명을 snake_case로 지어서 entity등 설정할 때 column name를 따로 명시해주는 것이 많이 번거로우신지에 대해서도 의견 여쭙고 싶습니다.

**Comment by JeongHyeongKim** [comment]
좋은 의견이네요

아직까진 써보면서 저는 큰 이슈 없이 잘 쓰긴 했지만, 해당 부분 우려 되시면 안쓰고 직접 설정해도 저는 무관합니다.

다른분들 의견이 궁금하네요

다만, typeorm-naming-strategies 패키지도 주 다운로드 회수가 7만회 정도 되고, 꾸준히 늘고 있는 것으로 보아 정상적으로 작동하는 케이스가 많기 때문에 늘고있지 않나 생각해봅니다.

선택은 여러분 몫이에요. 의논해서 결정해보아요

**Comment by jaryapp** [comment]
DB에서는 snake_case 코드 엔티티에서는 camelCaee 사용으로 결정
