### ISSUE TITLE
[server] 이미지 업로드 모듈

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#137]
## 📌 개요

NestJS에서 동작할 이미지 업로드 모듈을 구현합니다.

## 👩‍💻 기능 설명

- `multipart/form-data`로 전달되는 이미지 파일을 특정 디렉터리에 저장하고 접근할 수 있는 URL을 반환하는 API를 구현합니다.

### ✅ 참고 사항

파일 업로드 모듈로 `multer`를 많이 사용하는것 같은데 다른 더 좋은 대안이 있다면 그 방식으로 해도 됩니다!

- https://any-ting.tistory.com/121
- https://www.npmjs.com/package/multer

**Comment by JeongHyeongKim** [comment]
이미지 업로드 전 해당 파일을 어떤 저장소에 저장할 것이며, 최대 사이즈를 얼마까지 할 것인지에 대한 정보가 필요합니다.

**Comment by jaryapp** [comment]
@JeongHyeongKim 
장기적으로 봤을때 이미지만 저장하는 클라우드 인스턴스를 두는게 나을까요?
그리고 클라우드에 저장하는것과 로컬에 저장하는 것 두 구현 방식의 차이가 많이 날까요? (만약 큰 차이가 나지 않는다면 테스트 서버에서는 로컬방식으로 우선 구현하고 나중에 리얼배포전에 클라우드가 구축되면 저장소 위치를 바꾸는 방법도 생각하고 있습니다)

이미지 업로드 기능은 학생회에서 많이 사용하게 될것같습니다.

**Comment by jaryapp** [comment]
논의결과 AWS S3를 사용하게 될것 같습니다~
