### ISSUE TITLE
[삽질] 패키지 설치 오류

### ISSUE THREAD

**Issue by sween2591** [CMI-OSS/cbnu-alrami#143]
## 🤷 삽질 내용
packages/server로 이동하여 yarn add 패키지명 이나
yarn workspace server add 패키지명으로 
패키지 설치시 아래와 같은 오류가 발생하여
package.json에 수동으로 입력 후 yarn install로 적용하는 중입니다.
error라인에 막혀서 패키지가 설치가 안되는데 혹시 다른 분들은 잘되시나요?

### ✅ 참고 사항
![image](https://user-images.githubusercontent.com/61648828/161402325-c55168bb-b8d1-48a8-83be-734f01b2f112.png)

공유할 내용, 스크린샷 등을 넣어 주세요.

- 추가적인 공유가 필요한 사항은 Comment

**Comment by jaryapp** [comment]
저도 정확한 원인은 찾지못해서 임시방편으로 해결법 공유합니다.
1. 루트의 `yarn.lock` 지우고 다시 시도
https://github.com/yarnpkg/yarn/issues/7807#issuecomment-594636027

2. `yarn policy` 설정, 팀원들간에 `yarn`버전이 달라서 생길 수 있는 이슈라서 이를 맞추라는 뜻인듯?
https://github.com/yarnpkg/yarn/issues/7807#issuecomment-588632848
https://classic.yarnpkg.com/en/docs/cli/policies/

일단 1번으로 먼저 진행하고 이슈생기면 2번을 한번 파보겠습니다
