### ISSUE TITLE
[SETTING] 백엔드 response format 세팅 

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#146]
## ✨ What?

REST API 개발 시 response format을 통일한다. 

## 🛠 How?

- response dto를 이용해 REST API 응답을 통일한다. 
- 요청 처리에 실패한 경우를 컨트롤할 수 있도록 커스텀 예외 핸들러를 세팅한다. 
  - error message를 전역에서 사용할 수 있도록 세팅한다. 

### ✅ 참고 사항
>notion - 회의록 - 2022.04.03 주간회의 참고

- 페이징이 필요한 REST API response
`{ 
   "pagnation": {
        // 페이징 처리에 필요한 정보
   }
   "": {
       // API 요구 데이터
   }
}`

- 일반 REST API response
  - 성공
  `{
	// API 요구 데이터
}`
  - 실패
  `{
	"error":{
     "message": "실패 원인"
  }
}`

- 추가적인 공유가 필요한 사항은 Comment

**Comment by jaryapp** [comment]
### API 문서에 foramt 반영 상황
- [x] 보드 계층 조회
- [x] 보드별 게시물 목록 조회
- [x] 보드별 게시물 상세 조회
- [x] 코로나 일일 확진자수
- [x] 학사일정
- [x] 학생식당 목록
- [x] 학생식당 메뉴
- [x] 관리자 목록 조회

### 추후 작업예정
- [ ] 보드별 게시물 목록 조회(페이지네이션용 포맷추가)

**Comment by jaryapp** [comment]
보드별 게시물 목록 조회에서 페이지네이션 제외 하고 포맷 변경 완료했습니다~

**Comment by EunjiShin** [comment]
- 방식 1
  - `HttpException`을 상속받아 커스텀 exception을 만들어 사용
- 방식 2
  - Exception filter를 이용, response를 레이어 단위로 컨트롤 
  - 보통 `main.ts`에서 `useGlobalFilters()` 메소드로 전역 예외 핸들링을 구현하지만, exception filter를 구현하는 경우 main에서 의존성 주입 불가능 
    - 예외 필터는 예외가 발생한 모듈 외부에서 수행되기 때문
    - custom providers를 이용, `module` 파일에서 적용 권장 
- 레퍼런스 
  - https://docs.nestjs.com/exception-filters 
  - https://tristy.tistory.com/52
