### ISSUE TITLE
webpack -> vite 번들링 서버 마이그레이션 검토

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#171]
## 📌 개요 
 -  webpack -> vite 번들링 서버 마이그레이션 검토
 
## 👩‍💻 기능 설명
  - [x] webpack의 문제 공부
  - [x] vite 장단점 공부
  - [x] vite 예제 실습
  - [x] admin 마이그레이션
  - [x] mobile 마이그레이션

**Comment by kingyong9169** [comment]
@thdwlsgus0 스캇 저도 vite 공부해보고 싶은데 공부하실 때 같이 참여해도 될까요??

**Comment by thdwlsgus0** [comment]
@kingyong9169 

좋죠 당연히 ㅎㅎㅎ
저는 사실 틈틈히 보려고 했어요! 
블로그에 정리해서 공유해드리려고 했는데 음.. 어떤 식으로 진행하면 좋을까용

**Comment by kingyong9169** [comment]
> @kingyong9169
> 
> 좋죠 당연히 ㅎㅎㅎ 저는 사실 틈틈히 보려고 했어요! 블로그에 정리해서 공유해드리려고 했는데 음.. 어떤 식으로 진행하면 좋을까용

스읍 생각해보니 마땅히 방법이 없군요ㅋㅋㅋㅋㅋ 스캇이 정리해주시면 재밌게 보도록 하겠습니다!

**Comment by nohgijin** [comment]
이거 제가 가져가게 되었습니다~ PR에 관련 상세 내용 남겨두도록 할게요 :D
