### ISSUE TITLE
[server] DB 테이블명 및 필드명 snake_case로 통일, typeorm-naming-strategies 적용

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#177]
## ✨ What?

- DB 테이블 및 필드명이 PascalCase 혹은 caelCase 로 되어있어서 snake_case로 변환
- 관련 이슈 https://github.com/CMI-OSS/cbnu-alrami/issues/134

## 🛠 How?

- DB 관련 설정은 직접 변경
- `typeorm-naming-strategies` 모듈에서 `SnakeNamingStrategy`를 적용하여 DB에서는 snake_case로 코드에서는  camelCase 사용하도록 설정

### ✅ 참고 사항
https://www.npmjs.com/package/typeorm-naming-strategies

**Comment by sween2591** [comment]
#185 번 이슈 하면서 적용하겠습니다.
server/i185 브랜치에서 작업중입니다.
