### ISSUE TITLE
[FIX] 학사일정 스크래퍼 네이밍 수정

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#18]
## ✨ What?
학사일정 스크래퍼 year.js 스크립트 파일에서 scripts라는 프로퍼티를 사용하게 되면 차후 중복될 우려가 있어 네이밍 수정이 필요합니다.

## 🛠 How?
`year.js`의 `scripts`->`years`로 수정합니다.

### AS-IS
`scripts`

### TO-BE
`years`
### ✅ 참고 사항

```
years: [
    {
      year: 2020,
      key: "1728",
    },
    {
      year: 2021,
      key: "1804",
    },
  ]
```

**Comment by jaryapp** [comment]
엇 이슈 만드셨군요.. 누락된 코드는 기존 브랜치에 push해서 PR올리셔도 되는데..ㅎㅎ 죄송하네유..

**Comment by kingyong9169** [comment]
> 엇 이슈 만드셨군요.. 누락된 코드는 기존 브랜치에 push해서 PR올리셔도 되는데..ㅎㅎ 죄송하네유..

엇 그러게여.. 괜히 일을 만들었네여..ㅎㅎ 다음부터는 그렇게 하겠습니당
