### ISSUE TITLE
[제안] Admin pages, routes 파일구조 제안

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#214]
## 💁‍♀️ 제안 사항

``` tsx
import { Routes, Route } from "react-router-dom";

import { BoardWrite } from "src/components/Board";

export default function ScraperPage() {
  return (
    <Routes>
      <Route path="/list" element />
      <Route path="/write" element={<BoardWrite />} />
    </Routes>
  );
}
```
위와 같이 기존 `Admin`의 `pages`의 코드 구조는 `routes`의 의미를 갖고 있어 `pages`의 기능을 하지 못하는 느낌입니다. 그리고 실질적인 `page`는 `component`에서 관리되고 있습니다. 재사용성을 위한 `components`는 `pages`또한 담당하고 있어 그 의미가 줄어드는 것 같습니다.

따라서 기존 `components`에 있는 `page`는 따로 `pages`에서 관리하고 기존 `pages`는 `routes`로 분리하는 것을 제안합니다. 많은 의견 부탁드립니다!

### ✅ 참고 사항
@CMI-OSS/cbnu_alrami_fe 
- 추가적인 공유가 필요한 사항은 Comment

**Comment by nohgijin** [comment]
네 좋아요~ 이번에 vite로 번들링 도구 변경하면서 admin 폴더 구조를 봤는데, 저도 비슷한 바를 느꼈어요!
제가 생각하는 좋은 방법은 App.tsx 내에서 Route처리를 모두 다 하고
이 처리시에 필요한 path와 component는 router.ts를 만들어서 constant처럼 관리해도 좋을 것 같아요 
이렇게 하면 Page 폴더 자체가 필요없어지겠네요~

Ex) App.tsx
```
<Routes>
  <Route path={pathName} element={ComponentName} />
</Routes>
```

Ex) router.ts
```
export const RouteName={
  root: '/', 
  login:'/login',
}
```

**Comment by nohgijin** [comment]
그리고 담당자가 왜 front 모두 다 되어있는걸까요 ~?

**Comment by kingyong9169** [comment]
> 그리고 담당자가 왜 front 모두 다 되어있는걸까요 ~?

앗 fe모두 알림이 가도록 할 의도였습니다 바꾸겠습니다~

**Comment by soonitoon** [comment]
저도 Admin 작업하면서 폴더 구조 정리가 필요하다고 느꼈습니다. 동의합니다!

**Comment by thdwlsgus0** [comment]
저도 이 부분에 동의합니다~
