### ISSUE TITLE
[제안] 충림이 프로젝트를 모노레포로 관리하려고 합니다.

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#23]
## 💁‍♀️ 제안 사항

충림이와 관련된 모든 패키지들을 하나의 레파지토리(모노레포)에서 관리하려고 합니다.

모든 패키지에서 typescript를 주언어로 사용하게되면서 공통적으로 사용하게되는 모듈(타입)들이 많이 생기게 될것 같아요.
따라서 공통으로 사용되는 타입 혹은 모듈들을 공통 패키지에서 작업하고 하나의 레포에서 이슈를 관리하는게 히스토리를 파악하기 쉽다고 판단했습니다.

대략적인 구조는 다음과 같습니다.
```
cbnu-alrami
ㄴ packages
  ㄴ server (DB연동, API서버, 소켓서버 back-end)
  ㄴ mobile (충림이 모바일 front-end)
  ㄴ scraper (공지사항, 학사일정, 식단 등 스크래퍼)
  ㄴ admin (관리자 페이지)
  ㄴ shard(공통 모듈)
```

cbnu-alrami-scraper 레포가 현재 가장 활성화 되어있기 떄문에 cbnu-alrami로 이름을 변경하고 이 레포를 모노레포로 사용할 예정입니다.
기존 코드는 scraper와 management로 이관합니다.

모노레포 도구로는 `lerna`를 사용할 예정입니다.

### ✅ 참고 사항
https://simsimjae.medium.com/%EB%AA%A8%EB%85%B8%EB%A0%88%ED%8F%AC-252d7f11c6fa
https://y0c.github.io/2019/06/14/monorepo-tutorial/

질문 제안 등의 의견은 코멘트 부탁드립니다! 🙇

**Comment by kingyong9169** [comment]
`mobile`은 모바일 버전 웹이고 `pc`는 pc 버전 웹인가요?

**Comment by jaryapp** [comment]
> `mobile`은 모바일 버전 웹이고 `pc`는 pc 버전 웹인가요?

@kingyong9169 
넴 맞습니다. `pc`버전의 패지키명을 `pc`로 할지 다른걸로 할지 고민중인데 좋은 이름 있을까요

**Comment by nohgijin** [comment]
good. 근데 management 보다는 bakcoffice나 office같은 이름이 더 좋을것같아요

**Comment by jaryapp** [comment]
> good. 근데 management 보다는 bakcoffice나 office같은 이름이 더 좋을것같아요

@nohgijin 
좋은것 같습니다. 아니면 지금은 해당 패키지에서 스크래퍼 관리만 하게되겠지만 나중에 여기서 충림이 서비스에 관한 관리도 할 수 있게끔 하는 의미에서 admin으로 하는건 어떨까여?

**Comment by kingyong9169** [comment]
> > `mobile`은 모바일 버전 웹이고 `pc`는 pc 버전 웹인가요?
> 
> @kingyong9169 넴 맞습니다. `pc`버전의 패지키명을 `pc`로 할지 다른걸로 할지 고민중인데 좋은 이름 있을까요

음 `Desktop`?? 근데 데크스탑은 뭔가 응용 프로그램같아서 `pc`가 더 좋은 이름 같습니당

**Comment by jaryapp** [comment]
> > > `mobile`은 모바일 버전 웹이고 `pc`는 pc 버전 웹인가요?
> > 
> > 
> > @kingyong9169 넴 맞습니다. `pc`버전의 패지키명을 `pc`로 할지 다른걸로 할지 고민중인데 좋은 이름 있을까요
> 
> 음 `Desktop`?? 근데 데크스탑은 뭔가 응용 프로그램같아서 `pc`가 더 좋은 이름 같습니당

@kingyong9169 

오 저는 pc보다`desktop`이좋은것 같은데여? ㅎㅎ 좀 더 고민해보고 괜찮은게 없으면 이걸루 할게욤

**Comment by nohgijin** [comment]
> 음 `Desktop`?? 근데 데크스탑은 뭔가 응용 프로그램같아서 `pc`가 더 좋은 이름 같습니당

동감.. 먼가 pc버전 mobile버전 이렇게 익숙해서 그런가 desktop은 이질감느껴져요 😉

**Comment by jaryapp** [comment]
> > 음 `Desktop`?? 근데 데크스탑은 뭔가 응용 프로그램같아서 `pc`가 더 좋은 이름 같습니당
> 
> 동감.. 먼가 pc버전 mobile버전 이렇게 익숙해서 그런가 desktop은 이질감느껴져요 😉

그런가여? `pc`랑 `desktop`둘다 패키지명으로 사용되는것을 별로 못보긴해서 애매하군여
