### ISSUE TITLE
[server] dev-server CORS

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#239]
## 📌 문제 상황

`dev-server`에 이미지 업로드시에 CORS에러

## 🐛 발생 위치

<img width="723" alt="image" src="https://user-images.githubusercontent.com/49256790/169652056-d9feea26-8c4e-49b0-a6e9-553df6f19dcb.png">

### ✅ 참고 스크린 샷

허용해야할 orgin
- dev-admin.cmi.kro.kr
- localhost:8000

**Comment by jaryapp** [comment]
`https://dev-admin.cmi.kro.kr/board/write` 파일 선택하기에서 이미지 업로드 요청 이후에 발생하는 오류입니다. 개발자도구에서 콘솔 혹은 Network 탭에서 확인 가능

**Comment by ionc635** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/80724255/169687963-aa3c1fe5-7154-4a98-bbc9-90f07567cb70.png">

@jaryapp 
제스.. 저는 오류가 다르게 나옵니다..?

**Comment by jaryapp** [comment]
@ionc635 
엇 제가 `env` 파일 설정을 잘못해서 다시 했더니 잘되네여 ㅎㅎ
local에서 안되는건 확인해봐야겠네용
