### ISSUE TITLE
[제안] 협업관련 변동사항

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#24]
# 💁‍♀️ 제안 사항

## 1. 깃모지
기존에는 커밋메시지에 `prefix`를 앞에 붙여주는 방식으로 룰을 정했는데
`prefix`대신 깃모지를 사용하게되면 히스토리를 파악하기 더 편하고 재밌을것 같다는 생각이 들었습니다.

### AS-IS
`{prefix}: {action} {subject} (#{issue_number})` 

### TO-BE
`{:gitmoji:}: {action} {subject}`

뒤에 이슈넘버를 붙이는게 약간 불필요한 작업같아서 뺼까 고민중입니다

ref.
[Gitmoji](https://gitmoji.dev/)
[Gitmoji 사용하기](https://treasurebear.tistory.com/70)

## 2. Squash merge
기존에는 일반 merge를 사용했는데 Squash merge를 사용하는게 더 깔끔하게 커밋로그를 관리할 수 있다는 생각이 들어서
Sqaush merge를 Default로 사용하려고 합니다.

[GitHub의 Merge, Squash and Merge, Rebase and Merge 정확히 이해하기](https://meetup.toast.com/posts/122)

## 3. branch 룰
#23 
프로젝트를 모노래포로 관리하게되면 feature브랜치를 만들때 prefix를 사용하지 않고 패키지명을 붙이는게 관리하는 측면에서 더 좋을것 같다는 생각이 들었습니다.

### AS-IS
`{prefix}/i{issue_number}`

### TO-BE
`{package}/i{issue_number}-{자유}`
예:) mobile과 관련된 작업이라면 `mobile/i20-home` scraper패키지와 관련된 작업이라면 `scraper/i10-notice`

**Comment by nohgijin** [comment]
1. 깃모지는 저는 좀 싫어합니다(ㅋㅋ) 개인의 취향일것같은데 뭔가 전문성이 떨어지는 느낌
2. 제가 지금 플젝을 안보고 있는데 i를 붙여야하나요? 전 # 로 하면 자동으로 가서 #를 붙이는게 좋네여

**Comment by jaryapp** [comment]
> 1. 깃모지는 저는 좀 싫어합니다(ㅋㅋ) 개인의 취향일것같은데 뭔가 전문성이 떨어지는 느낌
> 2. 제가 지금 플젝을 안보고 있는데 i를 붙여야하나요? 전 # 로 하면 자동으로 가서 #를 붙이는게 좋네여

@nohgijin

1. 저도 처음 깃모지를 보고 이게뭐지 싶었는데 현재 회사에서 사용하고 있어서 익숙해지다보니 커밋로그 파악하기도 좋고, prefix들보다 더 분류가 많아서 커밋타입을 선택할때 더 좋았던것 같습니다ㅎㅎ

2. 여기서 i가 붙는건 브랜치인데 브랜치에서도 #이 적용이 되나여?

**Comment by nohgijin** [comment]
> > 1. 깃모지는 저는 좀 싫어합니다(ㅋㅋ) 개인의 취향일것같은데 뭔가 전문성이 떨어지는 느낌
> > 2. 제가 지금 플젝을 안보고 있는데 i를 붙여야하나요? 전 # 로 하면 자동으로 가서 #를 붙이는게 좋네여
> 
> @nohgijin
> 
> 1. 저도 처음 깃모지를 보고 이게뭐지 싶었는데 현재 회사에서 사용하고 있어서 익숙해지다보니 커밋로그 파악하기도 좋고, prefix들보다 더 분류가 많아서 커밋타입을 선택할때 더 좋았던것 같습니다ㅎㅎ
> 2. 여기서 i가 붙는건 브랜치인데 브랜치에서도 #이 적용이 되나여?
1. 전 여전히 깃모지 싫어요 (그리고 맥 사용자가 아니신 분도 배려 해야한다고 생각합니다)
2. 근데 지금 보니까 커밋에 i 안붙이던대요 ..? 먼소린지 잘 모르겠어요 ㅠ

**Comment by jaryapp** [comment]
> > > 1. 깃모지는 저는 좀 싫어합니다(ㅋㅋ) 개인의 취향일것같은데 뭔가 전문성이 떨어지는 느낌
> > > 2. 제가 지금 플젝을 안보고 있는데 i를 붙여야하나요? 전 # 로 하면 자동으로 가서 #를 붙이는게 좋네여
> > 
> > 
> > @nohgijin
> > 
> > 1. 저도 처음 깃모지를 보고 이게뭐지 싶었는데 현재 회사에서 사용하고 있어서 익숙해지다보니 커밋로그 파악하기도 좋고, prefix들보다 더 분류가 많아서 커밋타입을 선택할때 더 좋았던것 같습니다ㅎㅎ
> > 2. 여기서 i가 붙는건 브랜치인데 브랜치에서도 #이 적용이 되나여?
> 
> 1. 전 여전히 깃모지 싫어요 (그리고 맥 사용자가 아니신 분도 배려 해야한다고 생각합니다)
> 2. 근데 지금 보니까 커밋에 i 안붙이던대요 ..? 먼소린지 잘 모르겠어요 ㅠ

넵 알겠습니다 그럼 아쉽지만 깃모지는 보류하는걸로 하죠ㅠ
아 커밋에는 prefix: subject (#23) 이런 형태가 룰인데 (#23)자체를 뺄가하는 고민이었습니다.
왜냐하면 풀리퀘스트 템플릿에 반드시 이슈명을 적기로 되어있고, squash merge할때 그 풀리퀘스트의 번호를 자동완성 시켜줘서 굳이 필요없을것 같다는 생각이 들었습니다

**Comment by jaryapp** [comment]
1번은 보류 2,3번은 적용하는것으로 하고 이슈 닫겠습니다.
