### ISSUE TITLE
[mobile] 공통 mixin 추가

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#252]
## 📌 개요
- css 속성 중 position은 mixin으로 사용할 수 있을 것 같음.

## 👩‍💻 기능 설명
- [x] position mixin

**Comment by nohgijin** [comment]
typograph가 mixin으로 설정되어있는데 어떤게 더 필요하셔서 font mixin이 있는건지 알 수 있을까욤~?

**Comment by thdwlsgus0** [comment]
@nohgijin font-weight 부분은 없는 것 같아서용.. 수정하려고 했어용

**Comment by nohgijin** [comment]
음 font-weight면 그냥 주는게 더 편하지 않나요?? 구체적으로 어떤 건지 잘 모르겠어서요! typograph를 수정하신다는 건가요?

**Comment by thdwlsgus0** [comment]
@nohgijin 
넵넵 저희 회사에서 font-weight까지 mixin으로 만들었었는데 편리하게 사용하고 있어서 typograph에 font-weight를 적용하려고 했어요~
현재처럼 font-weight를 따로 주는 방법을 적용해도 괜찮을 것 같긴 합니다.
