### ISSUE TITLE
[SETTING] scraper redux, redux-thunk 세팅

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#27]
## ✨ What?
스크래퍼에서 사용할 redux, thunk 초기세팅입니다.

## 🛠 How?
"redux" npm 라이브러리를 사용하며 createStore, subscribe, dispatch 메소드를 사용합니다.

### ✅ 참고 사항
https://redux.js.org/usage/usage-with-typescript#type-checking-redux-thunks
https://velog.io/@cyongchoi/Redux-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-Vanila-JS
https://enumclass.tistory.com/234
https://react.vlpt.us/redux-middleware/04-redux-thunk.html
https://velog.io/@mokyoungg/Redux-Redux-thunk#5-3-action%EC%9C%BC%EB%A1%9C-api-%ED%98%B8%EC%B6%9C-srcactionsindexjs
https://react.vlpt.us/using-typescript/06-ts-redux-middleware.html

**Comment by jaryapp** [comment]
@kingyong9169 
브루니 현재 redux는 scraper에만 적용하면되고 management는 리액트 세팅후에 할 예정이에요~~
