### ISSUE TITLE
[server] 공지사항 조회 관련 API 개발 

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#304]
## 📌 개요

- 충림이 홈 대시보드에 필요한 공지사항 조회 API들을 개발합니다. 

## 👩‍💻 기능 설명

- [x] 유저가 북마크한 공지사항 리스트 조회 API 
- [x] 유저가 구독한 board의 최신 공지사항 Top 5 리스트 조회 API 

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by EunjiShin** [comment]
@jaryapp 
최신 공지사항은 `article`의 `date`, `created_at`, `updated_at` 중 어느 필드를 기준으로 삼아야 할까요?
공지사항 등록일자 기준으로 생각하면 `date` 필드를 사용하는게 맞는데, **공지사항이 수정 된 경우**도 고려해야 하나 싶어서요. 
(기존 등록되었던 공지사항 내용이 수정된 경우, 최신 공지사항으로 보는게 맞는지 🧐)

**Comment by EunjiShin** [comment]
또 공지사항 내용이 수정된 경우, 스크랩퍼가

1. `새로운 공지사항`이라고 판단하는지 
2. `동일 공지사항이 update` 되었다고 판단하는지 
3. 변경 사항을 `인지 못하는지`

도 궁금합니다!

**Comment by jaryapp** [comment]
@EunjiShin 
> 최신 공지사항은 article의 date, created_at, updated_at 중 어느 필드를 기준으로 삼아야 할까요?
공지사항 등록일자 기준으로 생각하면 date 필드를 사용하는게 맞는데, 공지사항이 수정 된 경우도 고려해야 하나 싶어서요.
(기존 등록되었던 공지사항 내용이 수정된 경우, 최신 공지사항으로 보는게 맞는지 🧐)

`date`로 삼는게 맞을것 같아요 admin을 통해 작성된 게시물(학생회 공지사항)같은 경우는 `date === created_at` 이지만, 스크래퍼가 수집한 게시물은 `date(실제 게시판에 작성된 시간)`, `createad_at(충림이 DB에 들어온 시간)` 이기 때문에 `date`를 기준으로 정렬하는게 맞는것 같습니다 ㅎㅎ

> 또 공지사항 내용이 수정된 경우, 스크랩퍼가
> 1. 새로운 공지사항이라고 판단하는지
> 2. 동일 공지사항이 update 되었다고 판단하는지
> 3. 변경 사항을 인지 못하는지도
> 궁금합니다!

스크핑 게시물에 대해 수정했는지 판단하는 로직은 신경써야할게 많아서 현재는 수정 체크를 하지 않고 있어요 => 스크래핑한 게시물에 대한 수정은 신경쓰지 않아도 됩니다.
