### ISSUE TITLE
[setting] eslint-config-cmi 사용하기

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#344]
## 📌 개요
[eslint-config-cmi](https://www.npmjs.com/package/eslint-config-cmi) 를 만들어서 배포되어 있는데요, 실제 프로젝트에 적용해보려고 합니다.

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by jaryapp** [comment]
이게 모에여? cmi 전용 eslint 룰?

**Comment by nohgijin** [comment]
넹 cmi에서 쓰는 eslint 패키지로 빼놨어요 @jaryapp
