### ISSUE TITLE
Collaboration Guide

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#35]
기본적으로 [공통 협업 가이드](https://github.com/CMI-OSS/common/issues/1#issue-1007285363) 문서를 따르되 프로젝트 특성상 추가적인 가이드를 제시

### Branch
- 브랜치 생성규칙은 `{package}/i{issue_number}`와 같은 형태로 작성합니다. 
`e.g. mobile/i30, admin/i27, scraper/i40`
- 모든 작업에 이슈를 작성할 필요는 없습니다. (리팩토링/간단한 수정/코드 스타일 정리 등) 이슈를 작성하지 않고 작업할때는 `{package}/{simple keyword}`로 브랜치를 생성후에 PR을 날리면됩니다. `e.g mobile/refactor-notice-scraper `

### Pull Request
- 풀리퀘스트 제목은 `[{package}] {content}`로 작성합니다.
- 풀리퀘스트 제목에도 **한글**사용이 가능합니다.
`e.g. [mobile] 공지사항 컴포넌트 수정 `

### Issue
이슈 제목 앞에 `prefix`를 붙이지 않아도 됩니다 (선택)

**Comment by soonitoon** [comment]
혹시 제가 까먹을까봐 11/17 회의에서 트레져가 짚어준 컨벤션 부분들도 댓글로 올려놓겠습니다~

- 컴포넌트 프롭 타입 정의할 때 `componentNameProps`와 같은 긴 이름 대신 짧게 `Props`이라고 이름 짓기.
- React Hook는 컴포넌트 최상단에 모아서 작성할 것(디버깅 & 리펙토링이 수윌함.).
- CSS에서 같은 컬러를 명도만 달리해서 만들 때는 100부터 - 900까지 숫자로 명도를 표현함.
    - ex) grey.$100 grey.$200 등
- CSS에서 홈페이지에 두루 쓰이는 메인 컬러를 지정할 때는 `primary` 변수명 사용(충림이의 경우 자주색이 해당됨.).

**Comment by jaryapp** [comment]
### Front-end 

#### 네이밍 컨벤션
- 함수명, 변수명 등 default naming -  `camelCase`
- 리액트 컴포넌트명 - `PascalCase`
- SCSS class  - `kebab-case`
- SCSS variable - `kebab-case`

#### 스타일 컨벤션
- 태그 선택자는 지양하고 클래스 선택자를 지향

**Comment by jaryapp** [comment]
### Back-end 

#### 네이밍 컨벤션
- DB Schema - `snake_case` - 코드단에서는 `camelCase`
