### ISSUE TITLE
[Suggest] FE static 데이터 폴더 관리

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#365]
## 💁‍♀️ 제안 사항

프론트엔드 static 데이터 폴더 관리 제안입니다!

### ✅ 참고 사항

static하게 사용할 데이터는 `constants`라는 폴더를 만들어서 관리하는게 어떨지 의견을 여쭙고 싶습니다! 더 좋은 네이밍이 있으시다면 부탁드립니다~!
@CMI-OSS/cbnu_alrami_fe 

- 추가적인 공유가 필요한 사항은 Comment

**Comment by nohgijin** [comment]
스태틱하게 쓰면 사용하는 컴포넌트에서 정의하는 어떠세요?

**Comment by kingyong9169** [comment]
> 스태틱하게 쓰면 사용하는 컴포넌트에서 정의하는 어떠세요? 

오홍 사용하는 컴포넌트 폴더 안에서 constants.ts로 정의하고 사용하는 건 어떨까요?

**Comment by nohgijin** [comment]
음.. 개인적으로 어차피 ui로직에 필요한 constant들은 그냥 컴포넌트에 정의를 하는게 오히려 편하더라구요 
말씀하신것처럼 컴포넌트 폴더안에 constant.ts를 만들면 너무 무분별한 constant들이 만들어져서요. 
저도 원래 root에서 constant를 만들어서 썼었는데 어차피 constant도 ui로직이라고 생각이 들어서 그냥 컴포넌트에 쓰는 건 어떨까 생각합니다!

**Comment by nohgijin** [comment]
프론트 회의시간에 정했습니다 ㅎㅎ
컴포넌트 폴더 하위에 constant 만들어주시고 export 시켜주세요~
@CMI-OSS/cbnu_alrami_fe

**Comment by kingyong9169** [comment]
> 

추가적으로 **3번이상** 사용되는 것은 `src/constants`에 정의하고 **2번** 까지는 컴포넌트 폴더 하위에 `constants`만들기로 했습니다!
