### ISSUE TITLE
[mobile] atomic 디자인에 맞게 상태 로직 제거 필요

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#382]
## 📌 개요
- `atomic` 디자인에 맞게 상태 로직을 제거할 필요가 있음
- `Chips`
- `PlaceTemplate`
- `Chips` -> `ChipGroup`로 변경 필요

## 👩‍💻 기능 설명
- [x] `Chips` -> `ChipGroup`로 변경
- [x] `placeTemplate` 수정
- [x] path variable -> query parameter로 수정 (ex. place?position=all)
     - redux-persist를 이용한 새로고침 적용 구현

**Comment by nohgijin** [comment]
ChipList대신 ChipGroup에 넣으시는건 어떠신가요?

**Comment by thdwlsgus0** [comment]
@nohgijin 

ChipGroup에 넣겠습니다 ㅎㅎ
