### ISSUE TITLE
[mobile] 아이콘 SVG height 프롭에 "auto" 대신 "100%" 사용하기

### ISSUE THREAD

**Issue by soonitoon** [CMI-OSS/cbnu-alrami#433]
## 📌 문제 상황

- 현재 `dev` 브랜치 기준으로, 모바일 페이지에서 콘솔에 해당 오류가 출력됩니다.
```
Error: <svg> attribute height: Expected length, "auto"
```
- [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg)에 검색해보니, `SVG` 태그의 `height` 속성은 `length` 혹은 `percentage` 값만 받을 수 있는 것 같습니다.
- 같은 에러 메시지로 올라온 [이슈 내용](https://github.com/boopathi/react-svg-loader/issues/194)을 보면 `auto` 키워드 대신 `100%`를 써도 같은 효과를 얻을 수 있는 것 같습니다(실제로 해봐도 결과가 똑같고, 해당 에러 메시지도 사라졌습니다!).
- 그래서 `height="auto"`로 설정되어 있는 아이콘들을 모두 `height="100%"`로 바꾸는 작업을 제안드립니다.

## 🐛 발생 위치

SVG 태그의 height 속성이 auto로 설정된 아이콘이 쓰인 모바일 페이지

### ✅ 참고 스크린 샷

![image](https://user-images.githubusercontent.com/71015915/183913944-bfbfcdae-32e6-44d9-899e-b9f90d094cd9.png)

**Comment by nohgijin** [comment]
넵 좋습니다!

**Comment by soonitoon** [comment]
넵~ PR로 올리겠습니다!
