### ISSUE TITLE
[server] 유저가 알림 or 구독 설정한 게시판 조회 API res 추가

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#453]
## 📌 개요

- 프론트엔드 요청! 

## 👩‍💻 기능 설명

- 유저가 알림 or 구독 설정한 게시판 조회 API res에 구독 중인 board의 origin board (루트 보드)를 추가합니다 

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by nohgijin** [comment]
close시키겠습니당 감사합니다 ㅎ
