### ISSUE TITLE
[Mobile] 에러 바운더리 세팅

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#476]
## 📌 개요

에러 바운더리 세팅

## 👩‍💻 기능 설명

에러 바운더리 세팅

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by nohgijin** [comment]
[이거](https://github.com/CMI-OSS/cbnu-alrami/issues/395)랑 같은 이슈인가요?

**Comment by thdwlsgus0** [comment]
@nohgijin @kingyong9169 그런 것 같네용! 하나만 관리해도 좋을 것 같습니다.

**Comment by kingyong9169** [comment]
@nohgijin @thdwlsgus0 앗 같은 이슈네용 이 이슈로 브랜치 파서 다른 이슈는 닫겠습니다!
