### ISSUE TITLE
[admin] 관리자 페이지 로그인

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#52]
## 📌 개요

관리자 페이지 로그인을 구현합니다.

## 👩‍💻 기능 설명

- `JWT` 토큰을 이용하여 관리자 페이지의 로그인을 구현합니다.

#### 로그인 프로세스
1. 프론트에서 아이디, 비밀번호를 백엔드로 전달 (`/api/login`)
2. 백엔드에서 아이디, 비밀번호 유효한지 확인 (유효하지 않다면 에러코드 반환) - 프론트에서는 사용자에게 에러 메시지 보여주기
3. 유효하다면 JWT 발급
4. JWT를 프론트엔드 쪽으로 다시 `response`
5. 프론트에서는 발급받은 JWT값을 기본 헤더값으로 지정 (헤더명은 `x-access-token, x-refresh-token`) `localStorage`에도 JWT를 저장하여 프론트가 켜질때 `localStorage`에 있는 JWT값을 기본 헤더값으로 지정
6. 프론트에서는 매번 API 요청할때마다 JWT값이 서버쪽으로 자동 전달됨(기본 헤더로 설정했으므로)
7. 백엔드에서는 미들웨어를 통해서 프론트의 헤더(`{"x-access-token": JWT1, "x-refresh-token": JWT2}`)의 값을 확인하여 사용자 구분 및 로그인 상황 체크

#### 로그아웃 프로세스
1. `localStroage`에 있는 JWT값 삭제

#### 쿠키를 사용하지 않는 이유
보통 JWT는 쿠키를 통해 전달되는 경우가 많은데 쿠키를 사용하려면 결론적으로 `https`를 사용해야하기 때문..
그래서 직접 헤더로 삽입하는 방식을 채택

#### 서버 통신
`axios` 모듈 사용

**Comment by kingyong9169** [comment]
> ## 📌 개요
> 관리자 페이지 로그인을 구현합니다.
> 
> ## 👩‍💻 기능 설명
> * `JWT` 토큰을 이용하여 관리자 페이지의 로그인을 구현합니다.
> 
> #### 로그인 프로세스
> 1. 프론트에서 아이디, 비밀번호를 백엔드로 전달 (`/api/login`)
> 2. 백엔드에서 아이디, 비밀번호 유효한지 확인 (유효하지 않다면 에러코드 반환)
> 3. 유효하다면 JWT 발급
> 4. JWT를 프론트엔드 쪽으로 다시 `response`
> 5. 프론트에서는 발급받은 JWT값을 기본 헤더값으로 지정 (헤더명은 `authorization`) `localStorage`에도 JWT를 저장하여 프론트가 켜질때 `localStorage`의 있는 JWT값을 기본 헤더값으로 지정
> 6. 프론트에서는 매번 API 요청할때마다 JWT값이 서버쪽으로 자동 전달됨(기본 헤더로 설정했으므로)
> 7. 백엔드에서는 미들웨어를 통해서 프론트의 헤더(`{"authorization":JWT}`)의 값을 확인하여 사용자 구분 및 로그인 상황 체크
> 
> #### 로그아웃 프로세스
> 1. `localStroage`에 이는 JWT값 삭제
> 
> #### 쿠키를 사용하지 않는 이유
> 보통 JWT는 쿠키를 통해 전달되는 경우가 많은데 쿠키를 사용하려면 결론적으로 `https`를 사용해야하기 때문.. 그래서 직접 헤더로 삽입하는 방식을 채택
> 
> #### 서버 통신
> `axios` 모듈 사용

저희 서버에서 `x-access-token, x-refresh-token` 두 개를 보내줘서 헤더명을
```
{
    x-access-token: 
    x-refresh-token:
}
```
이렇게 하는거 어떤가요??

**Comment by jaryapp** [comment]
@kingyong9169 
좋습니다~~!

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
