### ISSUE TITLE
충림이v2 개발일정

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#54]
## 일정
12/16 ~ 12/22 - (dev환경) `admin` 및 `scraper` 종합 테스트
12/22 수요일  - (real환경) `admin`, `scraper` 배포
12/22 ~ - `admin`, `scraper`,`server`일부 모니터링 및 고도화 작업, `mobile`개발

2022년 2월중 - `ReactNative` or `Flutter` 어플 개발(웹뷰,FCM)
2022년 3월중 - 충림이v2 `mobile` 배포

### `scraper` 스크래핑 검증
- 공지사항 `scraper` 컨텐츠 내용까지 잘 긁어오는지 검증
- 일부 예외 사이트들도 처리해야함

### `admin` UI/UX 및 프론트 작업
- Redux/Redux-thunk 구축
- 시나리오 검색 및 필터링
- 시나리오 디테일 페이지
- 스크래퍼 관리자 도구

### 실시간 스크래퍼 관리 
- `scraper` <-> (socket)`server` <-> `admin`
- 데이터 구조 설계
- 소켓통신 구조 설계

### 데이터베이스 연동 및 REST API 구축
- 기존 mariaDB 연동 
- 신규 mongoDB 설계, 연동
- REST API 구축

### `mobile` 프론트 개발
- 프로젝트 셋업
- 스펙정의, UI/UX 기획
- 기존 기능들 개발~

개략적으로 개발일정을 잡았습니다
자세한 일정이나 사항들은 논의하면서 차차 맞춰가요~

**Comment by kingyong9169** [comment]
일정 짜시느라 너무 고생 많으셨슴다👍

**Comment by nohgijin** [comment]
`Fluttur`  -> `flutter` ㅎㅎ

**Comment by jaryapp** [comment]
v2기획이 변경됨에 따라 개발일정도 맞춰서 추후에 새로 업로드 하겠습니다 따라서 해당 이슈는 닫습니다
