### ISSUE TITLE
[server] auth 관련 mongoDB 모델 생성

### ISSUE THREAD

**Issue by sween2591** [CMI-OSS/cbnu-alrami#55]
## 📌 개요
user, refresh-token schema 추가
server dependency에 bcrypt, jsonwebtoken 모듈 추가 
server/utils/jwt.ts 추가

### user 스키마
username: String
password: String
createdAt, updatedAt

virtual.password.set() : 비밀번호 데이터 입력시 암호화되도록
schema.authenticate(): 비밀번호 암호화 한 후 검증 

### refresh-token 스키마
user: objectId, ref: User
value: String
createdAt: { index: {expires: 만료시간}

## 👩‍💻 기능 설명
1.mongoose 활용 shared/src/models에 @auth/스키마명.schema.js 추가
2.코드 상에서 호출할 모델명과 콜렉션 이름은 명명 규칙에 따라 단수형으로하며
3.스키마명->모두 소문자, -제거
4.모델명->카멜케이스로 자동 생성 

 ### user  
virtual 필드를 이용하여 세터를 지정해서 암호화되지 않은 암호를
암호화하여 저장

 ### refresh-token 
user와 짝지어서 검색을 해야하므로 user:1, value:1로 인덱싱, 각 인덱스별로 1개씩만 유효하므로 unique: true
createdAt에서 [만료기간 세팅](https://bloodguy.tistory.com/entry/MongoDB-document%EC%97%90-expire-time-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-expire-TTL) 을 통해 유효기간 만료 시 refresh-token자동 제거
jwt모듈에서 사용할 refresh-token 검색 및 삭제 static 메소드 추가

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
