### ISSUE TITLE
[server] auth API + jwt 구성

### ISSUE THREAD

**Issue by sween2591** [CMI-OSS/cbnu-alrami#56]
## 📌 개요

issue의 개요를 적어주세요.
 ### routes/auth
1. controller
2. middleware
3. index - API 라우팅

### shared/src/utils
1. jwt.ts
2. auth.ts //api API에서 호출하는 인증미들웨어

### jwt.ts
말그대로 요청 사이에 검증 함수를 미리 설정해두는 파일,
authenticate 미들웨어에서 사용하는 메소드 제공
signAccessToken - res.data.xAccessToken에 넣을 토큰(payload, privatekey, jwt알고리즘객체를 인코딩) 생성
signRefreshToken - res.data.xRefreshToken에 넣을 토큰(user_id, privatekey) 생성
verifyAccessToken - header['x-access-token']에 있는 문자열 해독하여 payload 반환
verifyRefreshToken - header['x-refresh-token']에 있는 문자열 해독한 후 db에 유효한 토큰인지 검증한 후 _id 반환

###shared/auth.ts --api 서버 호출용
autheticate - req에 user정보가 포함될 경우 access token 유효하지 않으면 유저정보 삭제
isAuthenticated - req에 원래부터 user정보가 없는 경우 
공통 - /token/validate API호출하여 토큰 정보 검증 후 payload해석하여 반환된 값을 req.user 객체에 넣음

### auth API
(여기서 호출하는 isAuthenticated는 shared/auth.ts에 있는 게 아니라 auth에 있는 미들웨어입니다.)
/login - controller.login 
/logout - isAuthenticated -> controller.logout
/token/validate - isAuthenticated -> controller.validateToken - api API에서 인증하기위해 호출

### auth/controller.ts
login - req.body의 user_id와 password를 mongoDB에서 검색하여 있으면 signAccessToken signRefreshToken 호출하여
           프론트에서 헤더로 사용할 수 있도록 res.data.xAccessToken, res.data.xRefreshToken으로 반환.
logout - refreshtoken을 DB에서 삭제 후 res 반환
validateToken - 검증용 컨트롤러이며 api API에서 활용함

### ✅ 참고 사항

공유할 내용, 스크린샷 등을 넣어 주세요.

- 추가적인 공유가 필요한 사항은 Comment

**Comment by kingyong9169** [comment]
로그인할 때
```
{
    "id": ,
    "password"
}
```
형태로 보내도록 했는데 user_id가 편하신가요??

**Comment by sween2591** [comment]
mongoDB에서 자동으로 매겨지는 게 _id : objectId 여서 혼동 될 것 같아서 username이 좋습니다.

**Comment by kingyong9169** [comment]
> 

앗 글쿤요 근데 프론트 코드에서는 id 관련 변수들이 많아서 `username`보다는 `userId`가 더 좋은 것 같아서 혹시 어떠신가요?

**Comment by jaryapp** [comment]
제 생각에도 `userId` 혹은 `loginId`가 좋을것 같습니다 그리구 변수명과 객체속성은 카멜표기법을 따라주세요!

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
