### ISSUE TITLE
[제안] admin 로그아웃 기능

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#57]
## 💁‍♀️ 제안 사항

`로그아웃`버튼이 필요한데 시나리오 페이지에서 해야할 것 같아 제안하게 되었습니다. 저 혹은 @soonitoon이 작업하면 될 것 같습니다! 이미 수니툰이 시나리오 페이지 개발 중에 있어 상대적으로 일이 적은 제가 해도 좋을 것 같고 수니툰이 해도 좋을 것 같습니다!

### ✅ 참고 사항

`로그아웃` 버튼을 누르면 로컬스토리지에 있는 `x-access-token, x-refresh-token`을 remove하고 로그인 페이지로 이동하게 하는 작업입니다.

```
localStorage.removeItem("x-access-token");
localStorage.removeItem("x-refresh-token");
```
후 Redirect to 사용하시면 될 것 같습니다.

**Comment by soonitoon** [comment]
미처 생각을 못 했는데 제가 이번 작업 PR에 추가해놓겠습니다~

**Comment by jaryapp** [comment]
해당작업은 @kingyong9169 가 하는것으로 변경했습니다~

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
