### ISSUE TITLE
[mobile] 캠퍼스맵 server2 리팩토링

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#591]
## 📌 개요
api 리팩토링으로 인해서 도메인과 일부 url 변경 -> 대응 필요

## 👩‍💻 기능 설명
- [x] /place/school
- [x] /place/school/{area}
- [] /school/{id}
    - /school/{id}만 일단 연결
    - 추가 정보 필요
- [] 코드 리팩토링
- [] 최종 점검 

### ✅ 참고 사항
- 이미지는 아직 적용이 안됨 향후 추가 필요

**Comment by thdwlsgus0** [comment]
@jaryapp 

제스~ /school/id api 연결하고 있는데요~ 

이 정보 이외에 건물에 대한 기본 정보(이름, 상세설명, 이미지)도 id url 접근시에 조회 가능했으면 좋겠는데 
나중에 이미지랑 같이 추가 가능하실까용??
일단 `place/school`, `place/school/{area}` api는 연결 완료했습니다.

<img width="864" alt="스크린샷 2023-02-05 오후 3 08 33" src="https://user-images.githubusercontent.com/22065725/216804584-5fc68c38-b410-4da4-a408-d96cf2c15e95.png">

**Comment by jaryapp** [comment]
@thdwlsgus0 
안녕하세요 스캇 이슈 확인해서 API 추가했습니다~
이걸루 사용해주시면 됩니다!
![image](https://user-images.githubusercontent.com/49256790/216808440-4d93227f-ee41-4726-ad55-fba5d6cd9e71.png)

그리고 리팩토링할때 API는 따로 정의하지 않고, 여깄는거 사용하시면 됩니다~
https://github.com/CMI-OSS/cbnu-alrami/blob/83227dc1f203538ea01f826c27f3a6413bf22d33/packages/shared/src/swagger-api/generated/services/PlaceApiService.ts#L24-L41

FE회의때 한번 더 설명드릴게요~
