### ISSUE TITLE
[Mobile] Deffered component

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#646]
## 👩‍💻 기능 설명

0.3초 뒤에 로딩 스피너를 보여주도록 구현합니다.

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by nohgijin** [comment]
0.3s 로 하기로 했었나요? 2초로 그때 회의시간에 조정한 것 같아서요~

**Comment by kingyong9169** [comment]
> 0.3s 로 하기로 했었나요? 2초로 그때 회의시간에 조정한 것 같아서요~

2초로 하기에는 너무 긴 것 같아서요ㅠㅠ 2초 이상 로딩이 생기는 유저가 발생했을 때 2초 동안 빈 화면을 보여주는 건 유저에게 치명적이라는 생각입니다. 0.3초가 너무 짧다면 길어도 1초로 하는게 좋을 것 같다는 생각입니다. Sentry같은 모니터링 툴로 수치를 확인해서 결정하는 것이 가장 좋다고 생각합니다! 아래는 참고한 문서입니다.

https://tech.kakaopay.com/post/skeleton-ui-idea/#react-suspense%EC%99%80-%ED%95%A8%EA%BB%98-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

**Comment by nohgijin** [comment]
@kingyong9169 네~ 회의때 한 내용이랑 달라서 여쭤봤어요. 일단 저희는 센트리가 없으니 ㅎ api response duration를 보고 판단하는게 좋을것같네요. 지금 articles기준 0.3s가 나오니 1s가 적절할것같아요~
