### ISSUE TITLE
[mobile] 공지사항 디테일 페이지 SSR 전환

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#652]
## 👩‍💻 기능 설명

- [ ] ssr 전환
- [x] meta 태그 확인

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by kingyong9169** [comment]
SSR사용없이 pre-rendering을 구현하는건 어떨까요? https://tlog.tammolo.com/posts/react-ssr-02 좋은 문서가 있습니다!
