### ISSUE TITLE
S3에 운영에 필요한 이미지 올리기

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#661]
## 👩‍💻 기능 설명

S3에 운영에 필요한 이미지들 올려놓고 사용하기

**Comment by nohgijin** [comment]
충림이 파비콘 필요합니다~

**Comment by nohgijin** [comment]
![Group 73](https://user-images.githubusercontent.com/38103082/221411003-1a37d70d-d7cf-4783-917d-c3718ffb629a.png)

**Comment by jaryapp** [comment]
@nohgijin
S3 URL: https://cbnu-cmi.s3.ap-northeast-2.amazonaws.com/images/1678586426871.png

**Comment by jaryapp** [comment]
https://cbnu-cmi.s3.ap-northeast-2.amazonaws.com/images/1687599140710.png

**Comment by jaryapp** [comment]
https://cbnu-cmi.s3.ap-northeast-2.amazonaws.com/images/1687599898542.png

**Comment by jaryapp** [comment]
https://cbnu-cmi.s3.ap-northeast-2.amazonaws.com/images/1687599898609.png
