### ISSUE TITLE
[mobile] 아이폰의 경우 버튼 색깔 파란색

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#673]
### ✅ 참고 스크린 샷

![IMG_851B5563FD8E-1](https://user-images.githubusercontent.com/38103082/222949116-ad70d4ad-0360-41c0-b421-cd3cad6fa24b.jpeg)

- 추가적인 공유가 필요한 사항은 Comment

**Comment by thdwlsgus0** [comment]
@nohgijin 
이거 색상 명시적으로 주면 되영! 
아이폰에서 색상 명시적으로 주지 않으면 발생하는 이슈입니다!
