### ISSUE TITLE
[Mobile] iOS 노치 디자인 대응

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#690]
## 👩‍💻 기능 설명

Ios 노치 디자인 대응

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by thdwlsgus0** [comment]
@kingyong9169  
브루니 이거 safe-area에 대해서 한 번 공부해보세요~
https://wit.nts-corp.com/2019/10/24/5731

**Comment by kingyong9169** [comment]
## 대응 필요한 기기 목록

### X

- [ ] X
- [ ] XR
- [ ] XS
- [ ] XS Max

### 11

- [ ] 11
- [ ] 11 Pro
- [ ] 11 Pro Max

### 12

- [ ] 12 mini
- [ ] 12
- [ ] 12 Pro
- [ ] 12 Pro Max

### 13

- [ ] 13 mini
- [ ] 13
- [ ] 13 Pro
- [ ] 13 Pro Max

### 14

- [ ] 14
- [ ] 14 Plus
- [ ] 14 Pro
- [ ] 14 Pro Max

**Comment by thdwlsgus0** [comment]
x 11 12는 빼고 13 14만 해봅시당
safe-area 값만 추가해주면 왠만하면 다 대응되요~

**Comment by kingyong9169** [comment]
safe-area-inset-* 속성을 쓰면 기기에 맞춰서 알아서 값이 들어가네요~
