### ISSUE TITLE
[제안] admin useSelect 상태 조회 파일 관리

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#72]
한 가지 제안사항이 있습니다! @CMI-OSS/cbnu_alrami_fe 

각 slice에서 state에 대한 타입을 미리 정의하고
`export const view = (state: RootState) => state.view;`
컴포넌트에서
`const { scraper } = useAppSelector(view);`
이렇게 사용하니까 굉장히 편리하더라구요!
하지만 나중에 컴포넌트에서 여러 slice의 상태를 조회할텐데 이렇게 되면 여러 slice를 import하는 것이 불편할 것 같아서 각 slice의 state에 대한 모든 타입을 하나의 파일에서 관리하면 어떨까 하고 여쭤봅니다!

_Originally posted by @kingyong9169 in https://github.com/CMI-OSS/cbnu-alrami/pull/67#discussion_r764268824_

**Comment by jaryapp** [comment]
오 이렇게 코멘트를 바로 이슈화활수도 있군요 좋네요 ㅎㅎ

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
