### ISSUE TITLE
[QA] 구독 설정이 바로 적용되지 않음

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#772]
## 📍 재현 위치

![image](https://user-images.githubusercontent.com/49256790/229348987-1d693314-afdd-49aa-bde5-a5412f98ce54.png)

## 📌 상황 설명

- 공지사항 설정 > 구독 설정 아이콘 클릭 후 무반응
- 새로 앱을 실행하면 다시 켜짐

**Comment by nohgijin** [comment]
이거 #763에서 하고있어영
->복잡한것같아서 따로할게요

**Comment by jaryapp** [comment]
related #763

**Comment by jaryapp** [comment]
@nohgijin
이거 서버 문제 였을수도 있다는 생각이 드네여 서버 속도가 빨라지니까 미재현돼여
확인후에 괜찮으면 close 고고하시져

**Comment by nohgijin** [comment]
@jaryapp 네 구독 여부 자체를 api response로 판단하는거여서 클라이언트에서 따로 관리하려고 했었어요 확인해보니 충분히 빠른 것 같아서 닫을게요
