### ISSUE TITLE
[QA] 홈 환경 설정 버튼 색 다름

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#773]
## 📍 재현 위치

<img width="416" alt="image" src="https://user-images.githubusercontent.com/38103082/229349446-71090197-109e-42ae-aa24-2a4bdc252c4e.png">

## 📌 상황 설명

- 색깔이 다름

**Comment by kingyong9169** [comment]
1. 처음 들어오면 홈 버튼에 색상이 없음(/라서 그런 것 같아요!)
2. 푸터의 다른 버튼 눌렀다가 홈버튼을 누르면 이상 없음

**Comment by nohgijin** [comment]
#763 에서 같이 할게요 여기서 버튼도 하고있어서요 @kingyong9169
