### ISSUE TITLE
[QA] 홈 기온별 옷차림 반응형 지원

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#774]
## 📍 재현 위치

아이폰 8

<img src="https://user-images.githubusercontent.com/62797441/229349796-feefd766-212f-444a-8274-06e722405fb5.PNG" width=500 />

## 📌 상황 설명

홈 화면 -> 기온별 옷차림 클릭했을 때, UI가 깨짐

**Comment by soonitoon** [comment]
화면 세로 길이가 짧은 기기에서도 위쪽 마진을 유지하고, 밑부분을 스크롤하여 볼 수 있도록 수정하겠습니다~
