### ISSUE TITLE
[QA] 어플 첫 실행시 일정에서 "없음" 화면 출력

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#775]
## 📍 재현 위치

https://user-images.githubusercontent.com/38103085/229349900-a02a391a-f1b9-419c-b8a5-9e64fdcd2a11.MP4

## 📌 상황 설명

1. 어플 실행 
2. 일정 탭 선택
3. "없음" 화면이 일정 시간 동안 출력됨

**Comment by kingyong9169** [comment]
확인했습니다! 이거 제가 개선할게요!
컴포넌트에서 AsyncBoundary 사용하면 될 것 같습니다~!
