### ISSUE TITLE
[QA] 공지사항 가이드 이미지 깨짐

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#776]
## 📍 재현 위치

![IMG_6553](https://user-images.githubusercontent.com/38103085/229350000-8e3ba11e-354b-4eb5-8ae3-91c6468896ab.PNG)

## 📌 상황 설명

1. 공지사항 탭 접속
2. 위에 첨부한 것처럼, 가이드라인 이미지의 글자 부분 픽셀이 깨짐

### ✅ 참고

아이폰 12 pro 사용 중

**Comment by kingyong9169** [comment]
이거 플록스한테 부탁드려야겠네요
