### ISSUE TITLE
[QA] 식단 탭에서 식단이 없을 때 표시되는 포크숟가락 이미지 화질이 낮음

### ISSUE THREAD

**Issue by soonitoon** [CMI-OSS/cbnu-alrami#777]
## 📍 재현 위치

충림이 식단 탭에서 식단이 없을 때

## 📌 상황 설명
![IMG_072663F11CC4-1](https://user-images.githubusercontent.com/71015915/229350085-03039d14-4572-4a1f-8156-2b4f81e19356.jpeg)

다른 페이지의 아이콘과 다르게 포크 숫가락 아이콘만 화질이 낮게 보이는 것 같습니다.

**Comment by kingyong9169** [comment]
이거 플록스한테 부탁드려야겠네요
