### ISSUE TITLE
[QA] 서버 변경사항 (좋아요 등)이 UI에 바로 반영되지 않습니다

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#778]
## 📍 재현 위치

https://user-images.githubusercontent.com/38103085/229350146-2367541a-5840-4f77-ac7e-4734207f46cd.MP4

## 📌 상황 설명

(자세한 내용은 위의 동영상 참고해주세요!)

1. 특정 공지사항의 좋아요을 취소해서 1개가 된 상황
2. 공지사항 상세 페이지에는 1개로 잘 출력됨
3. 공지사항 리스트 뷰로 넘어가면, 취소하기 전인 2개로 출력됨
4. 마찬가지로, 해당 공지사항에 다시 좋아요를 추가해서 2개가 된 경우 상세페이지에는 2개로 출력됨
5. 인기 공지사항 리스트 뷰로 넘어가면, 좋아요를 추가하기 전인 1개로 출력되며 순위에도 변동이 없음

**Comment by nohgijin** [comment]
#763

**Comment by nohgijin** [comment]
related https://github.com/CMI-OSS/cbnu-alrami/issues/763
