### ISSUE TITLE
[QA] 모든 공지사항에 title NN 제약 조건 추가 제안

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#779]
## 📍 재현 위치

![IMG_DC76F9A3C719-1](https://user-images.githubusercontent.com/38103085/229350414-55cc0712-a503-45bf-b42c-bc0ba3ab4ab7.jpeg)

## 📌 상황 설명

현재, 첨부한 사진처럼 `제목이 없는 공지사항`을 충림이에 등록할 수 있습니다.
이 경우 리스트 뷰 등에서 아무 제목이 출력되지 않아, 사용자가 의아하게 생각할 수 있을 것 같아요.

제목을 필수 값으로 설정하거나, 또는 default 값을 설정하면 좋을 것 같습니다.

**Comment by nohgijin** [comment]
제목을 서버단에서 필수로 해주셔야 할 것 같긴 한데
클라이언트에서는 '제목이 없는 공지사항입니다' 라고 보여줄게요~

**Comment by jaryapp** [comment]
@EunjiShin  @nohgijin
서버에서 title 혹은 content가 nullable은 아닌데 admin에서 보내줄때 빈 string  ` `으로 보내줘서 그런것 같습니다
admin에서 입력하지 않으면 에러메시지 노출되도록 수정했습니다
https://github.com/CMI-OSS/cbnu-alrami/pull/847
