### ISSUE TITLE
[QA] 푸시 알림이 왔을 때, 뒤로가기 버튼이 동작하지 않습니다.

### ISSUE THREAD

**Issue by EunjiShin** [CMI-OSS/cbnu-alrami#782]
## 📍 재현 위치

https://user-images.githubusercontent.com/38103085/229350765-5700f433-9bfb-48e9-b825-2477733aacc3.MP4

## 📌 상황 설명

1. 어플 실행 X 중, 푸시 알림 발생 (앱을 아예 종료한 경우)
2. 푸시 알림을 클릭해 해당 공지사항의 상세 페이지로 이동
3. 좌측 상단에 있는 뒤로가기 버튼 클릭이 동작하지 않음 (클릭해도 반응 X)

**Comment by jaryapp** [comment]
게시판 목록을 통하지 않고, 게시물 페이지로 바로 접근했을때 발생하는 이슈로 파악됩니다.
이때는 이전 페이지가 존재하지 않으면, 뒤로가기시에 홈으로 이동시키면 될것같아요

history.state.idx가 0인경우 이전 페이지가 존재하지 않다고 볼 수 있을것 같습니다
![image](https://user-images.githubusercontent.com/49256790/229373641-ddc84df6-ec0c-45fe-b734-451c0aafe05a.png)
