### ISSUE TITLE
[QA] Map, Place에서 로딩일 때, 없음으로 나타나서 페이지 전체를 가림

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#783]
## 📌 상황 설명

Map, Place에서 로딩일 때, 없음으로 나타나서 페이지 전체를 가림

### ✅ 참고

AsyncBoundary를 사용하면 될 것 같습니다.

**Comment by thdwlsgus0** [comment]
@kingyong9169 이거 혹시 어디서 발생하는지 알 수 있을까요?

**Comment by kingyong9169** [comment]
@thdwlsgus0 Place Detail 들어갈 때, Chip 클릭(E, N, S구역)할 때 일어납니다!
