### ISSUE TITLE
[QA] 인기, 최신 게시판 안내 툴팁 UI 제안

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#791]
## 📍 재현 위치

- https://www.dev-mobile.cmiteam.kr/home

![image](https://user-images.githubusercontent.com/49256790/229366756-be589b14-fcb6-4281-9a99-3f948aca0246.png)

## 📌 상황 설명

홈화면 하단 공지사항 카드안 노출되는 인기/최신에 대한 안내가 있으면 좋아요 유도 및 UX에 좋을것 같습니다. (컴포넌트는 툴팁 제안)

#### 툴팁 안내 문구 제안
-  인기 게시판은 전체 게시판중 최근 2주동안 좋아요와 조회수가 높은 공지가 추천됩니다.
- 최신 게시판은 구독한 게시판중 최신순서로 제공됩니다.

### ✅ 참고

[antd tooltip ui
](https://ant.design/components/tooltip)

**Comment by nohgijin** [comment]
![image](https://user-images.githubusercontent.com/38103082/229647484-5b08c1ed-e9f4-41cc-95f9-7f715bc9438b.png)

이런식으로 할게요~
