### ISSUE TITLE
[QA] 식당 선택 메뉴 가운데 정렬

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#802]
## 📍 재현 위치

<img width="709" alt="image" src="https://user-images.githubusercontent.com/49256790/229682297-d5c99e99-8106-4c3f-9d4d-3c89297815f5.png">

## 📌 상황 설명

식당 선택 부분이 가로가 넓을때도 가운데 정렬이 되어야합니다.

### ✅ 참고

<img width="236" alt="image" src="https://user-images.githubusercontent.com/49256790/229682505-d5e0506e-6288-40ac-93dd-9aa848425b32.png">

**Comment by thdwlsgus0** [comment]
@jaryapp 이건 제가 하겠슴다
