### ISSUE TITLE
[QA] 홈-대표식당 모달 오류

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#805]
## 📍 재현 위치

홈-공지사항-식당

## 📌 상황 설명
![KakaoTalk_20230404_145541619_02](https://user-images.githubusercontent.com/100134173/229702136-56b82681-38db-4b25-8eb3-0c56cda7df16.jpg)
대표식당 모달을 킨 상태에서 스크롤을 내리면 다음과 같은 화면이 뜹니다. 스크롤되지 않도록 수정 부탁드립니다.

**Comment by soonitoon** [comment]
제가 작업하겠습니다~
