### ISSUE TITLE
[QA] 일정 빈 화면 오류

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#806]
## 📍 재현 위치
일정

## 📌 상황 설명
![KakaoTalk_20230404_145541619_04](https://user-images.githubusercontent.com/100134173/229702513-1b835480-25b5-4a58-867b-60e49f66a39f.jpg)

![KakaoTalk_20230404_145541619_03](https://user-images.githubusercontent.com/100134173/229702577-ba04f0fd-e9d9-4d5b-830b-ad989feceec2.jpg)

일정 빈화면의 일러스트가 잘립니다. 끝까지 스크롤되도록 하여 그림이 잘리지 않도록 수정 부탁드립니다.

### ✅ 참고

https://www.figma.com/proto/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?node-id=6080-136&scaling=scale-down&page-id=2615%3A99

**Comment by soonitoon** [comment]
말씀하신대로 수정하겠습니다~
