### ISSUE TITLE
[QA] 홈 디자인 QA

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#807]
## 📍 재현 위치
홈

## 📌 상황 설명

- [x] 충림이 아이콘과 설정 버튼 정렬 조절
충림이 아이콘과 설정 버튼은 같은 세로위치에 있는데, 현재 충림이 앱에서는 세로 위치가 같지 않습니다.

- [x] -설정 아이콘 수정 (모양, 색)
색은 black 40으로 변경 부탁드립니다. 그리고 설정 아이콘은 2종류가 있는데, 선이 더 두꺼운 설정아이콘으로 수정 부탁드립니다. (피그마 댓글남김)

- [x] 날씨 카드 디자인 수정
현재 날씨카드는 "최저-최대 온도"와 "기온별 옷차림:이 같은 가로선에 정렬되어있는데, 둘은 같은 줄에 있지 않습니다.
그리고 "최저-최대 온도"와 "기온별 옷차림"의 폰트 사이즈는 regular/body 3으로 동일합니다.
그리고 "온도", "날씨 정보", "최저-최대 온도" 간의 세로 간격이 너무 넓습니다. 이 부분도 수정 부탁드립니다.

- [x] 식단 카드 디자인 수정
제목(예. 한빛식당 점심)의 폰트는 medium/ header 3, 시간의 폰트 크기는 regular/body1 입니다.
그리고 수정하기 아이콘 크기가 너무 작으니 더 키워주셨으면합니다.
수정하기 아이콘은 black 60, 시간 글씨는 black 50으로 수정 부탁드립니다.

- [x] 공지사항 카드 "공지사항 글씨" font weight 안들어감
폰트 사이즈는 적합하나, font weight가 들어가지 않았습니다. medium/header3으로 수정 부탁드립니다.

**Comment by soonitoon** [comment]
이것도 제가 담당한 부분이 많아 수정할 때 한 번에 처리하겠습니다.
