### ISSUE TITLE
[QA] 일정 디자인 QA

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#808]
## 📍 재현 위치

일정

## 📌 상황 설명

![KakaoTalk_20230404_145541619_03](https://user-images.githubusercontent.com/100134173/229707695-7cee061c-4a40-411d-b42e-85133157de5b.jpg)

회색 점을 해당 날짜에 더 근접하게 수정합니다.
근접성의 원리에 따르면, 가까이에 있는 물체일수록 더 연관성이 있다고합니다.
따라서 회색 점과 날짜의 관계성을 명확히 보여주기 위해 회색 점과 날짜의 간격을 수정해주시기 바랍니다.

### ✅ 참고

![ddddd](https://user-images.githubusercontent.com/100134173/229708624-fbdeb06a-9ef8-44b2-b402-712f3fc64301.PNG)

(https://www.figma.com/file/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?node-id=2615-99&t=WN0HsopAheBTAUHW-0)

**Comment by soonitoon** [comment]
처리하겠습니다~
