### ISSUE TITLE
[QA] 캠퍼스맵 디자인 QA

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#812]
## 📍 재현 위치

캠퍼스맵

## 📌 상황 설명

- [x] 캠퍼스맵 장소 리스트 배경색 수정

![KakaoTalk_20230404_155233890](https://user-images.githubusercontent.com/100134173/229712241-7e23f248-4814-40d0-9dd2-a6efe38819bd.jpg)

현재 장소의 배경 색은 background 20입니다.

- [x] 아이콘 확인

![KakaoTalk_20230404_155233890_01](https://user-images.githubusercontent.com/100134173/229712124-bfd36ee7-837c-46a6-8049-3797103b11e8.jpg)

디자인 가이드의 아이콘은 같은 굵기인데, 캠퍼스 맵에서는 다르게 나타나는 것 같습니다. 확인 부탁드립니다.

**Comment by thdwlsgus0** [comment]
@Phlox09022 

background-color 몇으로 적용되어야 하나요??
