### ISSUE TITLE
[QA] 일정에서 즐겨찾기 하지 않은 일정이 홈화면에 뜸

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#813]
## 📍 재현 위치

홈, 일정

## 📌 상황 설명

일정에서 아무 일정도 즐겨찾기 하지않았는데도 홈화면에는 그 날 모든 일정이 뜹니다.

**Comment by soonitoon** [comment]
플록스, 제가 이해하고 있는 동작이랑 플록스가 말씀하신 동작이 다른 것 같아서 말씀드려요.  저희 [정책서](https://jaryintro.notion.site/3c076894207440db9f68d3e576e08d36) 상에는 홈에 표시되는 일정 기능을 이렇게 설명하고 있거든요.

> 오늘 기준 일정이 보이며, 정렬은 개인 등록 일정에서 학사 일정 순으로 보임.

개인 일정을 등록하는 기능이 버전1에서 제외되면서 오늘 날짜에 포함되는 학사 일정을 모두 표시하면 되는 걸로 이해하고 있었어요.

혹시 이후 회의에서 즐겨찾기한 일정만 표시하기로 바뀐 적이 있었나요?

**Comment by Phlox09022** [comment]
제가 처음에 생각했던 것은 이 기능이었는데, 만약 정책이 바뀌었다면 이대로 진행해도 될 것 같습니다. 혹시 이 글 삭제하는 법을 아시나요?

**Comment by thdwlsgus0** [comment]
@Phlox09022 
삭제는 없고 이슈 닫으면 됩니다~!

**Comment by soonitoon** [comment]
제가 닫겠습니다~~
