### ISSUE TITLE
[QA] 홈 식단카드 중앙정렬됨

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#814]
## 📍 재현 위치

홈-식단카드

## 📌 상황 설명

식단이 한 줄일 경우, 본문 텍스트가 좌측정렬되지 않고 중앙정렬됩니다. 한 줄 식단도 좌측정렬되도록 수정 부탁드립니다,

### ✅ 참고
![KakaoTalk_20230404_160220374](https://user-images.githubusercontent.com/100134173/229714291-5f7df2bd-fe52-4b29-8604-b4b6d9fc13e0.jpg)

**Comment by soonitoon** [comment]
알겠습니다~
