### ISSUE TITLE
[QA] 대표식당 선택 모달에서 표시안함 선택 시 모달 띄우기

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#815]
## 📍 재현 위치

홈-대표식당 모달

## 📌 상황 설명

현재 대표식당 선택 모달에서 "표시안함"을 누르면 바로 창이 꺼지면서 다시 대표식당을 설정하는 방법을 알립니다.
그러나 "표시안함"을 선택했을 경우, 다시 대표식당을 설정하는 것은 번거로운 일입니다.
만약 이 옵션을 실수로 터치한다면 사용자 입장에서는 불편함을 느낄 것입니다.

따라서 "표시안함"외에 다른 옵션은 그대로 유지하되, "표시안함"을 선택했을 경우 "홈화면에 식단을 표시하지 않으시겠습니까?"라는 모달을 띄워 다시 한 번 의사를 묻는 것이 적절하다고 생각됩니다.

### ✅ 참고

![ddd](https://user-images.githubusercontent.com/100134173/229716172-42b85aae-a312-4b38-b287-08966ecd39c1.PNG)

https://www.figma.com/file/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?node-id=901%3A41&t=WN0HsopAheBTAUHW-1

**Comment by soonitoon** [comment]
그러면 '표시안함'을 선택했을 때 표시하는 기존 모달을 제거하고 새로 만들어주신 모달을 띄우면 될까요?

**Comment by Phlox09022** [comment]
기존 모달 위에 trasparent와 새로 만든 모달을 띄워주시면 됩니다!

-참고
https://www.figma.com/proto/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?node-id=6091-267&scaling=min-zoom&page-id=901%3A41

**Comment by soonitoon** [comment]
네 확인했습니다~
