### ISSUE TITLE
react-router-dom v6 업그레이드

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#83]
react-router-dom v6버전에서는 `Switch`가 `Routes`로 바뀌었는데 어떻게 하는 것이 좋을까요? @CMI-OSS/cbnu_alrami_fe

_Originally posted by @kingyong9169 in https://github.com/CMI-OSS/cbnu-alrami/pull/81#discussion_r775242297_

**Comment by thdwlsgus0** [comment]
이 부분은 제가 할게요~

**Comment by thdwlsgus0** [comment]
이거 생각보다 react-router-dom이랑 연관된 파일이 많아서 조금 살펴봐야겠네요 ㅠㅠ
