### ISSUE TITLE
css size 컨벤션 정하기

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#84]
맞아요 rem을 사용하는게 습관이 되어버렸네요 ㅎ;;
나중에 mobile 작업 시작하기전에 이런 컨벤션들도 같이 정하면 좋을것 같아요 ㅎㅎ

_Originally posted by @jaryapp in https://github.com/CMI-OSS/cbnu-alrami/pull/81#discussion_r775250272_

**Comment by nohgijin** [comment]
px로 작업
