### ISSUE TITLE
[QA] PC > 이미지 프리뷰 크기 제한

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#844]
## 📍 재현 위치

![image](https://user-images.githubusercontent.com/49256790/230394882-bae8cb3c-379f-40a9-8b61-bb284994e69f.png)

## 📌 상황 설명

PC에서 이미지 프리뷰를 볼때 화면이 전체가가려지는 현상이 있는데 
위 아래 닫기 버튼과 indicator 영역은 보이도록 height 제한이 필요할것 같습니다

#### mobile 버전
![image](https://user-images.githubusercontent.com/49256790/230395727-22308aeb-d48e-4df2-9c85-5fbc381d512e.png)

**Comment by nohgijin** [comment]
데스크탑에서는 이미지 저장 모달이 필요없다는 판단, 모달 미노출로 결정
