### ISSUE TITLE
[QA] 공지사항 북마크 토스트 메시지

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#846]
## 📍 재현 위치

![Apr-06-2023 22-59-15](https://user-images.githubusercontent.com/49256790/230400579-145f13f3-7fd8-4471-8759-e8594dc7c80b.gif)

## 📌 상황 설명

다른 버튼들은 토스트 메시지가 있는데 북마크만 토스트 메시지가 없어서 아쉽습니다. 북마크에도 토스트 메시지가 들어가면 좋을것 같아요~

제안 문구: 북마크에 추가되었습니다

**Comment by nohgijin** [comment]
추가시
공지사항이 북마크 되었습니다. 
해제시
공지사항이 북마크 해제되었습니다.
