### ISSUE TITLE
type, interface 하나로 통일

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#85]
하나로 통일하는게 좋겠죠! 저는 갠적으로 type을 많이 쓰긴 하지만, interface를 써도 별 상관은 없습니다.

_Originally posted by @nohgijin in https://github.com/CMI-OSS/cbnu-alrami/pull/81#discussion_r775251377_

**Comment by nohgijin** [comment]
type으로 통일하고 이슈 닫겠습니다
