### ISSUE TITLE
[mobile] 모바일 제스쳐 지원

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#850]
## 👩‍💻 기능 설명

- 뒤로가기 시 스와이프를 활용하여 갈 수 있도록 제스쳐 지원
### ✅ 참고 사항

https://hammerjs.github.io/

- 추가적인 공유가 필요한 사항은 Comment

**Comment by kingyong9169** [comment]
이거 배포 전에 하시는건가용?

**Comment by nohgijin** [comment]
@kingyong9169 여건되면 이번배포에서 나가보고 안되면 담배포때 최대한빠르게 나가보려구요! 생각보다 스와이프 안되는게 불편하더라구요 ㅠ
