### ISSUE TITLE
[QA] 공지사항 리스트 무한 스크롤 데이터 패칭시 공지사항 선택영역 깜빡임 현상

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#853]
## 📍 재현 위치

https://user-images.githubusercontent.com/49256790/230538928-64cb65b2-f56f-42bb-8cdb-693d506184f4.MP4

## 📌 상황 설명

공지사항 리스트에서 데이터 패칭시에 상위의 공지사항 선택영역이 깜빡거리는데 깜빡임을 없앨 수 있을까여

**Comment by nohgijin** [comment]
불가능이란읎다

**Comment by jaryapp** [comment]
web에서는 미재현 native에서만 재현

**Comment by thdwlsgus0** [comment]
저는 이거 앱에서도 괜찮고, 웹뷰에서도 괜찮은데 ios에서 확인하신건가요??

**Comment by nohgijin** [comment]
네 저도 ios였고 느리게 말고 완전완전완전 빠르게 내리면 재현되는 환경이에용

**Comment by kingyong9169** [comment]
푸터에서 공지사항 누르면 잠시 깜박이는 현상이 있는데 이것과도 연관이 있을 수도 있을 것 같네요..
저도 고민해보겠습니다!

**Comment by jaryapp** [comment]
@thdwlsgus0 @nohgijin @kingyong9169 
app뿐만 아니라 mobile safari에서도 재현되네여 클로이말대로 천천히 내리면 괜찮은데 빠르게 내려서 데이터를 fetching 해오기전에 스크롤을 더 당겨올때 재현되는것 같습니다

https://user-images.githubusercontent.com/49256790/230902193-f4c195be-7f03-4fd7-8b16-5113bcb66af6.mp4

**Comment by nohgijin** [comment]
어 루트마진 넣어서 패치 빨리되올줄알았는데 다시한번확인해볼게요
->일단 루트마진 좀 크게 넣었어요

**Comment by kingyong9169** [comment]
> 푸터에서 공지사항 누르면 잠시 깜박이는 현상이 있는데 이것과도 연관이 있을 수도 있을 것 같네요.. 저도 고민해보겠습니다!

푸터가 깜박이는 현상은 article들어오면 article/subscribe로 replace하면서 한 번 더 렌더링해서 그런 것 같아요
