### ISSUE TITLE
충림이v2 아이디어

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#86]
예상 날짜: 2022.01.08(토) 저녁

**FE** - Frontend
**BE** - Backend
**SP** - Scraper

- **충림이 리뉴얼(코드 마이그레이션, UI 변경 등) → FE,BE**
- **대시보드 페이지 → FE, BE**
- **주변 맛집 지도 → FE, BE**
- 공지사항 지원 영역 넓히기 → FE,BE,SP
    - 대학별 공지사항
    - 대학원(+ 부가 게시판)
    - 학생회
- pull to refresh → FE
- **공지사항 공유 → FE**
- 스켈레톤 UI (로딩) → FE
- 낮,밤 모드 → FE
- **충림이 PC버전 → FE(mobile로 대체)**
- 스크래퍼 **고도화 및 모니터링 사이트 개발 → FE,BE(진행중),SP**
- **캘린더 - 공휴일추가 → FE,BE**
- 검색 → FE,BE
- **Android, IOS 업데이트 → 리액트 네이티브 or 플러터**
- 데이터베이스 재설계(MariaDB, MongoDB) → BE
- 광고..🤔

----
아직 확정 스펙이 아니기 때문에 회의전까지 변동사항이 있을 수있습니다.
기능뿐만 아니라 충림이v2 개발에서 해보고 싶은것들이나 개선점도 있다면 자유롭게 코멘트 남겨주세요~

**Comment by thdwlsgus0** [comment]
광고는 구글 애드센스를 말씀하시는 걸까요?

**Comment by nohgijin** [comment]
SP는 뭘까요 ?

**Comment by jaryapp** [comment]
> 광고는 구글 애드센스를 말씀하시는 걸까요?

@thdwlsgus0 
넵 맞습니다 근데 웬만하면 안넣는 방향으로 가고 싶긴합니다

**Comment by jaryapp** [comment]
> SP는 뭘까요 ?

@nohgijin 
Scraper 입니다 ㅋㅋ FE,BE 처럼 두글자로 맞추려다 보니 혼란을 야기한것 같군여 
이 부분도 본문에 추가할게요

**Comment by thdwlsgus0** [comment]
> > 광고는 구글 애드센스를 말씀하시는 걸까요?
> 
> @thdwlsgus0 넵 맞습니다 근데 웬만하면 안넣는 방향으로 가고 싶긴합니다

광고는 보기에 불편하신 분도 있을 것 같아요~
서버 비용이 부족하거나 필요한 비용이 있으면 광고를 달 수는 있겠지만 학교에 필요한 정보를 제공하는 소프트웨어에서 단순히 이익을 챙기기위해서 다는 광고라면 좋지 못한 시선들이 많을 것 같아요 ㅎㅎ..

이 의견은 제 `개인적인 생각`입니다!

**Comment by jaryapp** [comment]
@thdwlsgus0 
맞습니다 저도 공익이 주목적인 어플이기도 하고 UI상으로도 웬만하면 넣고 싶진않습니다
말씀해주신것 처럼 혹시라도 광고를 달게 되더라도 사익이 목적이 아닌 모두 개발비용으로 지출될 예정입니다 현재는 제 개인 서버를 사용하고 있어서 별도의 서버비가 나가진 않지만 v2부터는 늘어나는 트래픽과 안정성을 생각해서 aws를 사용하려고 해요 단순계산 했을때 월3~4만원 정도로 생각하고 있구용
그리고 안드로이드는 멤버십이 평생이라서 한번만 내고 상관없는데 애플은 매년 13만원정도 멤버십 비용을 지불하고 있어요 ㅎㅎ;
운영에 필요한 비용은 전부 제 사비로 지출할 예정이어서 여러분께서는 신경안쓰셔도 되지만 제가 예상했던것보다 지출비용이 크다면 한번쯤은 고민을 해봐야겠습니다 ㅎㅎ 아니면 도네이션 받는 방식도 있구용

**Comment by thdwlsgus0** [comment]
> @thdwlsgus0 맞습니다 저도 공익이 주목적인 어플이기도 하고 UI상으로도 웬만하면 넣고 싶진않습니다 말씀해주신것 처럼 혹시라도 광고를 달게 되더라도 사익이 목적이 아닌 모두 개발비용으로 지출될 예정입니다 현재는 제 개인 서버를 사용하고 있어서 별도의 서버비가 나가진 않지만 v2부터는 늘어나는 트래픽과 안정성을 생각해서 aws를 사용하려고 해요 단순계산 했을때 월3~4만원 정도로 생각하고 있구용 그리고 안드로이드는 멤버십이 평생이라서 한번만 내고 상관없는데 애플은 매년 13만원정도 멤버십 비용을 지불하고 있어요 ㅎㅎ; 운영에 필요한 비용은 전부 제 사비로 지출할 예정이어서 여러분께서는 신경안쓰셔도 되지만 제가 예상했던것보다 지출비용이 크다면 한번쯤은 고민을 해봐야겠습니다 ㅎㅎ 아니면 도네이션 받는 방식도 있구용

만약 광고를 달게 되거나 도네이션을 받는 스탠스를 취하게 된다면 사용자에게 언급은 필요해보이네요

**Comment by jaryapp** [comment]
@thdwlsgus0 
넵 저도 사용자 입장에서 광고에 대해서 회의적인 입장이어서요 어쩔 수 없이 달게되더라도 목적과 내역을 투명하게 공개할 예정입니다 
그리고 트래픽이 어느정도 나올지 정확히 예측은 안되지만 웬만하면 없이 가려고 생각하고 있구요 팀원들과도 충분히 상의하고 결정할 예정이어서 이부분은 크게 걱정 안하셔도 됩니다 ㅎㅎ

**Comment by jaryapp** [comment]
@thdwlsgus0 
지금도 매년 13만원을 지출하고 있고 내년부터는 매년 50만원 가량의 지출을 감수할 마음이 있을 만큼 저한테는 매우 애정어린 프로젝트입니다 ㅠㅠ 충림이를 통해서 사적인 이득을 취할 생각은 전혀 없는데.. 단순히 이득이라고 언급하신부분은 조금 서운합니다 😢

**Comment by thdwlsgus0** [comment]
> @thdwlsgus0 지금도 매년 13만원을 지출하고 있고 내년부터는 매년 50만원 가량의 지출을 감수할 마음이 있을 만큼 저한테는 매우 애정어린 프로젝트입니다 ㅠㅠ 충림이를 통해서 사적인 이득을 취할 생각은 전혀 없는데.. 단순히 이득이라고 언급하신부분은 조금 서운합니다 😢

기분 나쁘셨다면 죄송해요.. 그럴 의도는 아니었는데.. ㅎ..
광고에 대해서 여쭤보길래 그런 의도가 혹시나 있으신가 해서 여쭤본 것입니다.

**Comment by jaryapp** [comment]
@thdwlsgus0 
넵 충분히 궁금하셨을 수 있다고 생각합니다 ㅎㅎ 평소에 지출이 있더라도 학생분들을 위해서 좋은 의도로 운영과 개발을 하는 자부심(?) 같은게 있었는데 그 말을 들으니 쬐에에끔 서운했습니다ㅎ 하지만 스캇도 좋은 의도로 의견 주신것 같아서 괜찮습니다!
앞으로도 좋은 의견 부탁드릴게요 : )

**Comment by sween2591** [comment]
저희 DB는 마리아DB에서 몽고로 전체 다 바꾸는건가요? 
저번에 필요한 부분에만 사용한다고 들었던 것 같긴한데 살짝 헷갈려서 확인차 여쭤봅니당!

**Comment by jaryapp** [comment]
@vcho1958 
> 저희 DB는 마리아DB에서 몽고로 전체 다 바꾸는건가요?
저번에 필요한 부분에만 사용한다고 들었던 것 같긴한데 살짝 헷갈려서 확인차 여쭤봅니당!

애드워드 말이 맞습니다 본문 내용이 예전 버전이라서 최신화가 안되어 있어요 ㅎㅎ 본문에 반영해놓을게요 감사합니당

**Comment by JeongHyeongKim** [comment]
> @thdwlsgus0 맞습니다 저도 공익이 주목적인 어플이기도 하고 UI상으로도 웬만하면 넣고 싶진않습니다 말씀해주신것 처럼 혹시라도 광고를 달게 되더라도 사익이 목적이 아닌 모두 개발비용으로 지출될 예정입니다 현재는 제 개인 서버를 사용하고 있어서 별도의 서버비가 나가진 않지만 v2부터는 늘어나는 트래픽과 안정성을 생각해서 aws를 사용하려고 해요 단순계산 했을때 월3~4만원 정도로 생각하고 있구용 그리고 안드로이드는 멤버십이 평생이라서 한번만 내고 상관없는데 애플은 매년 13만원정도 멤버십 비용을 지불하고 있어요 ㅎㅎ; 운영에 필요한 비용은 전부 제 사비로 지출할 예정이어서 여러분께서는 신경안쓰셔도 되지만 제가 예상했던것보다 지출비용이 크다면 한번쯤은 고민을 해봐야겠습니다 ㅎㅎ 아니면 도네이션 받는 방식도 있구용

한번씩 aws credit 받는 경우가 있는데 기회되면 드릴게요

**Comment by jaryapp** [comment]
@JeongHyeongKim 
오.. 넵 필요하면 말씀드릴게요 ㅎㅎ 감사합니다!

**Comment by nohgijin** [comment]
제스가 말씀해주셨지만, 처음 기획했을때부터 사용자에게 배포하기까지의 과정에서 많은 시간과 돈이 들었고 외주 개발자분, 외주 디자이너분과 컨택할때도 많은 업체를 만나고 비용을 산정하고, 이 비용을 학교측에 청구하는 과정에서 많은 공수가 들었습니다. 
뿐만아니라 홍보물을 만들고 홍보글을 쓰고 제가 아는 학교의 모든 지인분께 과단톡방에 홍보글 하나 올려달라고 많은 부탁을 드렸구요.

그래서 저는 광고를 붙일때 사용자에게 미안함을 느끼고 싶진 않아요...
제 개인적인 생각입니다..ㅎㅎ

**Comment by thdwlsgus0** [comment]
> 제스가 말씀해주셨지만, 처음 기획했을때부터 사용자에게 배포하기까지의 과정에서 많은 시간과 돈이 들었고 외주 개발자분, 외주 디자이너분과 컨택할때도 많은 업체를 만나고 비용을 산정하고, 이 비용을 학교측에 청구하는 과정에서 많은 공수가 들었습니다. 뿐만아니라 홍보물을 만들고 홍보글을 쓰고 제가 아는 학교의 모든 지인분께 과단톡방에 홍보글 하나 올려달라고 많은 부탁을 드렸구요.
> 
> 그래서 저는 광고를 붙일때 사용자에게 미안함을 느끼고 싶진 않아요... 제 개인적인 생각입니다..ㅎㅎ

이 부분은 제가 깊이 생각을 못했던 것 같네요
이 프로젝트가 두 분께 굉장히 의미있는 프로젝트일텐데 생각이 너무 짧았던 것  같습니다 ㅎㅎ..
