### ISSUE TITLE
[QA] 맵디테일 풀페이지헤더 배경 투명하게

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#864]
## 📌 상황 설명

<img width="449" alt="image" src="https://user-images.githubusercontent.com/38103082/230651870-29bdf384-9870-412e-9e38-76bbfe0aacee.png">

### ✅ 참고

- 풀페이지모달을 적용하면서 생긴 문제

**Comment by thdwlsgus0** [comment]
@nohgijin 이거 background:none이 적용되어있는 것 같은데 꼭 필요한건가요?? 
이것 때문에 발생하는 이슈인 것 같아서요 

<img width="1344" alt="스크린샷 2023-04-08 오후 1 33 49" src="https://user-images.githubusercontent.com/22065725/230703250-053dab59-7013-4a7f-af45-4ae15d0ce41c.png">
