### ISSUE TITLE
[QA] touch-action으로 인해 공지사항, 식단에서 ChipList, MenuList 스크롤이 안됨

### ISSUE THREAD

**Issue by kingyong9169** [CMI-OSS/cbnu-alrami#867]
## 📍 재현 위치

global.scss touch-action

추가로 global css는 admin에서도 사용하고 있어 모바일에서 필요한 css는 mobile.scss로 옮겨주시면 좋을 것 같습니다.

## 📌 상황 설명

touch-action으로 인해 공지사항, 식단에서 ChipList, MenuList 스크롤이 안됨

### touch-action 사용

https://user-images.githubusercontent.com/62797441/230702178-2a72d67f-3a5e-42af-94c7-d6cb25ae89e8.mov

### touch-action 제거

https://user-images.githubusercontent.com/62797441/230702182-20c76517-0101-4ddc-aab7-cd906323c8d7.mov

@nohgijin 제가 작업한 부분이 아니라 touch-action을 빼도 되는지 확신이 없어 확인 부탁드립니다!

**Comment by jaryapp** [comment]
https://user-images.githubusercontent.com/49256790/230704196-ff38f2c5-683a-4d38-a73d-c7b195ffaf85.MOV
