### ISSUE TITLE
[mobile] front-end 프로젝트 설계

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#87]
모바일 프로젝트 설계

### 디렉터리 구조 정하기
```
mobile
├── babel.config.js
├── node_modules
├── package.json
├── public
│   └── index.html
├── src
│   ├── App.tsx
│   ├── __mocks__
│   │   └── index.ts
│   ├── components
│   ├── hooks
│   ├── index.tsx
│   └── utils
├── tsconfig.json
└── webpack.config.js
```

### 개발 스펙 및 사용 라이브러리
React
Typescript
Webpack
Redux toolkit
Emotion 
day.js

**Comment by jaryapp** [comment]
Storybook
- 재사용 컴포넌트 만들어서 편리
- 디버깅
- 컴포넌트 기준을 잘 정해야함
- 따로 공수를 내야함(유지보수시 시간+@)

**Comment by jaryapp** [comment]
트레저 - page 폴더는 실무에서는 잘 안쓰이는것 같다
트레저 - rotues 디렉터리 선호
트레저 - 아토믹 디자인 해보고 싶다

스캇 - 아토믹 디자인을 할때 기준을 잘 정하는게 좋을것 같다

`{packages}/utils` - 패키지에서만 사용하는 유틸
`shared/utils` - 공용으로 사용하는 유틸

2개 이상의 packages에서 사용한는 utils은 shard/utils로 이동

컴포넌트 폴더
Component
 ㄴ index.ts 
 ㄴ Component.tsx
 ㄴ Component.style.ts
 ㄴ Component.stories.ts


테스트 도구는 자유

**Comment by jaryapp** [comment]
팀 소개 사이트 - Next.js

**Comment by nohgijin** [comment]
일단 제가 해보고싶은거! 
`디자인 시스템 구축(스토리북이 필요합니당)`
`싸이프레스로 주요기능 e2e테스트 해보기`
그리고 저희 회사 컴포넌트 구조는
```
Component
ㄴ atoms
  ㄴ Button
    ㄴ index.ts
    ㄴ Button.tsx
    ㄴ Button.style.ts
    ㄴ Button.stories.tsx
ㄴ molecules
ㄴ organisms
ㄴ templates
```
그리고 .. `BFF` 저도 해보고싶어요 :D 한번도 안해봐서

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 close합니다
