### ISSUE TITLE
[QA] 캘린더 이전 달, 이후 달 날짜 클릭시 인터렉션 제공 제안

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#896]
## 📍 재현 위치

https://www.dev-mobile.cmiteam.kr/calendar
<img width="415" alt="image" src="https://user-images.githubusercontent.com/38103082/230802200-4f7d43a9-22c9-4efb-a200-05a739615fce.png">

## 📌 상황 설명

유저 테스트를 하고 있는 상황입니다.
유저가 4월 10일 기준 5월 1일 ~ 5월 6일 클릭시, 3월 26일 ~ 3월 31일 클릭 시 아무런 인터렉션이 발생하지 않았습니다.
점이 있어서 자연스럽게 클릭했다고 하더라구요.

현재 월 기준 전달, 후달에 날짜를 클릭 하면 전달,후달로 이동하거나 
ui상에서 점을 빼는 방식도 좋을 것 같아서 제안해요~

**Comment by kingyong9169** [comment]
의견 공감합니다~

**Comment by soonitoon** [comment]
혹시 일정이 있는 전달이나 다음달 날짜를 클릭하면 현재달 날짜를 클릭했을 때와 똑같이 해당하는 일정 카드를 보여주는 건 어떨까요? 유저가 해당 날짜를 클릭했다는 건 그 일정이 궁금하기 때문일 것 같아서요~

**Comment by nohgijin** [comment]
@soonitoon 좋아용!
