### ISSUE TITLE
[QA] 홈 > 공지사항 리스트 마우스 스크롤 안됨 

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#898]
## 📍 재현 위치
홈 > 공지사항 리스트 마우스 스크롤 안됨 

## 📌 상황 설명
https://user-images.githubusercontent.com/22065725/230875992-a3557ab1-e5ca-4371-b534-6560cfa6c888.mov

### ✅ 참고
@CMI-OSS/cbnu_alrami_fe  이거 touch-action 속성을 important로 해줘서 발생한 이슈인 것 같은데
touch-action 제거해주면 해결될 것 같아요~

<img width="1411" alt="스크린샷 2023-04-10 오후 6 35 42" src="https://user-images.githubusercontent.com/22065725/230876043-b9cbee31-0367-4f22-83e5-aeb4711dd3e1.png">

**Comment by nohgijin** [comment]
https://github.com/CMI-OSS/cbnu-alrami/issues/867 중복이슈여서 닫습니다
스와이프때문에 저걸 쓴 거여서 생각보다 처리하는데 시간이 걸리네유~~ ㅠ
