### ISSUE TITLE
[QA] 일정 > 일정 내용이 중복되서 보여짐 

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#899]
## 📍 재현 위치
일정 페이지 

## 📌 상황 설명
- 일정 내용이 중복되서 보여짐

### ✅ 참고
<img width="310" alt="스크린샷 2023-04-10 오후 6 49 59" src="https://user-images.githubusercontent.com/22065725/230878543-4b44b95f-1e04-4e55-afe4-4a9e59f586cf.png">

**Comment by nohgijin** [comment]
@jaryapp 
<img width="565" alt="image" src="https://user-images.githubusercontent.com/38103082/230882529-a3a445f2-def1-4fd7-9127-b154cba2b8d4.png">

**Comment by soonitoon** [comment]
저도 확인했습니다. 뒷 일정에도 중복되는 데이터가 많은 것 같아요!

**Comment by jaryapp** [comment]
@nohgijin @soonitoon @thdwlsgus0 
스케줄 스크래퍼가 2번 실행돼서 그런것 같아여 ㅎ; 지금은 중복데이터 지웠습니다
