### ISSUE TITLE
[QA] 아이콘버튼 터치영역 넓히기

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#904]

**Comment by thdwlsgus0** [comment]
캠퍼스맵부터 아래 순서대로 체크해보겠습니다.

캠퍼스맵 > 식단 > 공지사항 > 일정 > 홈 > 설정

**Comment by nohgijin** [comment]
@thdwlsgus0 그럼 스쾃 단독 어사인으로 해놓을게용~ 👍🏻👍🏻

**Comment by thdwlsgus0** [comment]
@nohgijin 넵 여행 잘다녀오세요~

**Comment by nohgijin** [comment]
아 추가로 이번 기회에 아이콘버튼 컴포넌트를 만들고, 해당 컴포넌트에서 터치영역을 넓히면 좋을 것 같아요.
자세한건 메터로 대략적인 코드 예시 보내드릴게요!

**Comment by thdwlsgus0** [comment]
공통화하는건 배포 이후에 하면 어떨까 싶습니다.
컴포넌트 정리하면서 같이 작업하면 좋을 것 같아서요~

일단 이 순서대로 수정하겠습니다. 
https://github.com/CMI-OSS/cbnu-alrami/issues/904#issuecomment-1502596628
