### ISSUE TITLE
[QA] 홈>식당선택 모달 깨짐

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#908]
## 📍 재현 위치
/home 에서 식당 클릭 시

![image](https://user-images.githubusercontent.com/38103082/230916088-e176fdec-282a-4c47-825a-2bbf6694e5c9.png)

## 📌 상황 설명
취소 버튼이 깨져보여용

**Comment by thdwlsgus0** [comment]
이거 혹시 testflight에서 발생하는 이슈인가요??
일단 제 testflight 테스트에서는 홈화면 표시 안함 모달이 아래처럼 나오긴 합니다. (식당선택 모달은 정상 노출)
혹시 홈화면 표시 안함 모달도 확인가능할까요?? 
 
![KakaoTalk_Photo_2023-04-11-11-15-25](https://user-images.githubusercontent.com/22065725/231038086-5f5a2f6d-f3c0-4df6-a7fd-6eec4a62c6ab.jpeg)

**Comment by nohgijin** [comment]
![image](https://user-images.githubusercontent.com/38103082/231042873-b0391f1e-f988-405f-92bd-3c6dd8c34a3c.png)
네 테스트플라이트에요!

**Comment by soonitoon** [comment]
이거 버튼에 유저 에이전트 스타일이 입혀져서 그런 것 같은데, 제가 처리하겠습니다!

**Comment by thdwlsgus0** [comment]
@soonitoon 
혹시 이거 작업중이신가요?

**Comment by soonitoon** [comment]
이거 사실 해결 방법을 못 찾아서 고민하고 있었어요ㅠ 처음에는 단순히 유저 에이전트 스타일 때문이라고 생각했는데, 제 아이폰이나 시뮬레이터에서 돌려봐도 재현이 안 돼서요...

**Comment by thdwlsgus0** [comment]
@soonitoon testflight에서 재현이 안되는거죠??
저도 다시보니까 재현이 안되네요! 
아이폰이시죠?

**Comment by soonitoon** [comment]
네 아이폰 테스트플라이트에서 재현이 안 됐습니다!

**Comment by thdwlsgus0** [comment]
@soonitoon 

이거 제가 생각하기에는 border px을 소수점으로 줘서 
일부 브라우저나 기기에서 제대로 나오지 않는 현상인 것 같아요

소수점으로 주게 되면 브라우저나 기기에서는 올림이나 버림으로 처리한다고 하더라고요 (일관적이지 않은 ui를 만들 가능성이 높아요)
그래서 px로 줄 때는 소수점으로 주지 않는 것이 좋을 것 같아요.

- 0.3px일 때
<img width="1215" alt="스크린샷 2023-06-18 오후 4 46 06" src="https://github.com/CMI-OSS/cbnu-alrami/assets/22065725/6f4dcb40-1fff-4bc7-afad-263183009725">

- 1px일 때
<img width="1251" alt="스크린샷 2023-06-18 오후 4 46 38" src="https://github.com/CMI-OSS/cbnu-alrami/assets/22065725/959f68d5-2f2d-4c30-bdbc-903a88d2d685">

이 부분은 한 번 phlox와 상의를 해보면 좋을 것 같은데 일단 제가 pr 올려볼게요!
고민하시느라 정말 고생많으셨습니다!

**Comment by soonitoon** [comment]
아아 이게 소수점 문제일 줄은 몰랐네요...ㅠ 덕분에 찜찜했던 게 해결된 것 같습니다 ㅎㅎ 수고하셨습니다!
