### ISSUE TITLE
[mobile] footer 제작

### ISSUE THREAD

**Issue by nohgijin** [CMI-OSS/cbnu-alrami#91]
## 📌 개요

충림이에 들어가는 푸터를 개발합니다

## 👩‍💻 기능 설명

[개발할 기능에 대해서 설명해주세요
](https://www.figma.com/file/ENjDeiT5OstxlYvhzwR3Vy/%EC%B6%A9%EB%A6%BC%EC%9D%B4-UI?version-id=1418628222&node-id=0%3A1)

**Comment by jaryapp** [comment]
2개월 이상 논의되지 않는 이슈라서 `close`하고 작업 필요시에 `re-open` 혹은 새 이슈를 개설합니다.
