### ISSUE TITLE
[mobile] 충림이 PC로 접근시 앱으로 보기 가이드 토스트 노출

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#919]
### 피그마
<img width="240" alt="image" src="https://user-images.githubusercontent.com/49256790/231898094-6d82b712-ce56-4fc8-bee0-a094df0f44e4.png">

## 📌 상황 설명

`isWebview`가 아닐때 문구 노출하면 될듯
https://github.com/CMI-OSS/cbnu-alrami/blob/353a6235730d585e1eb2fb98fb27d17bc9648da7/packages/mobile/src/utils/webview.ts#L13

**Comment by thdwlsgus0** [comment]
@kingyong9169 
혹시 이거 작업중이신가요?

**Comment by kingyong9169** [comment]
> @kingyong9169 혹시 이거 작업중이신가요?

이 부분 빠르게 작업해서 PR 올릴게요

**Comment by nohgijin** [comment]
저번에 제가 했었는데 빠져있네요 ; 제가 가져가겠습니다~
