### ISSUE TITLE
[QA] PC > 공지사항 목록 인피니티 스크롤 미동작

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#927]
## 📍 재현 위치

![Apr-20-2023 05-54-20](https://user-images.githubusercontent.com/49256790/233197885-cffada3e-35bb-40e9-a359-c501646fbffb.gif)

## 📌 상황 설명

app에서는 동작하는데 pc에서는 미동작

**Comment by nohgijin** [comment]
@jaryapp 이거 지금도 안되는지 확인가능하실까요~?

**Comment by jaryapp** [comment]
@nohgijin 
재현안되네용 이슈 닫겠습니다~
