### ISSUE TITLE
[QA] 갤럭시 s8에서 충림이 실행이 안돼요

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#929]
## 📍 재현 위치

갤럭시 s8
![KakaoTalk_20230603_205950049](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/7ee323eb-db3c-45ba-bbce-3d14cd6674f3)

## 📌 상황 설명

갑자기 충림이의 모든 기능이 실행이 안돼요

**Comment by Phlox09022** [comment]
2023년 6월 3일 9시 18분에 해결됐습니다

**Comment by jaryapp** [comment]
https 인증서 발급 받느라구 잠깐 서버 중단했었습니다 ㅎㅎ;
