### ISSUE TITLE
충림이 v2 기획

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#93]
## 목표

- 학교생활에 유익한 정보들을 제공하여 삶의 질을 Upgrade
- 하루에 한번이상은 접속하는것을 목표
- 다운로드 수 10,000+ / MAU 7,500 목표+

## 비로그인

- 클라이언트 고유번호를 이용
    - 어플 네이티브 기능필요(안드로이드, ios uuid)

- 연동
    - 앱에서 웹에 연동할 수 있는 기능
    - 인증번호를 어플리케이션 발급
    - 인증 유효 시간 제한
    - 로그아웃
    

## 홈

- 충림이 메인 페이지
- 공지사항, 학사일정, 식당, 날씨등 학교 생활에 필요한 정보를 요약해서 보여주는 페이지

### 메인화면

1. 날씨 표시
    - 당일 청주 날씨 표시(...분캠)
    - 기온별 옷차림

        
2. 식단
    - 현재 시간 기준으로 아침/점심/저녁 메뉴가 달라짐
    - 메인화면에 표시할 식단 설정
3. 일정
    - 오늘이 소속된 일정 리스트(중요도 순)
4. 최근 공지사항(3~5개)
    - 구독중인 공지사항이 있다면 전체 공지사항중에 최근 공지사항
    - 없으면 충북대학교 공지사항
5. 충청북도 혹은 청주 코로나 현황판(선택)
    - 확진자수

### 메인화면

1. 공지사항 선택
    - 스크랩
    - 구독중인 공지사항 선택
    - 그룹핑 기능(확장)
    - 구독 및 알림 설정 기능
2. 공지사항 목록
3. 공지사항 카드
    - 제목
    - 공지사항 이름
    - 날짜
    - 조회수
    - 추천수
    - 읽음 표시
4. 알림 목록
    - 알림 히스토리

### 공지사항 설정

- 구독중인 공지사항 목록 확인
- 구독 ON/OFF 설정
- 공지사항 그룹핑
- 공지사항 추가

### 공지사항 목록

- 공지사항 카드 리스트
- 무한 스크롤
- 구독 및 알림설정
- pull to refresh 새로고침

### 공지사항 상세

- 제목
- 날짜
- 본문
- 실제 공지사항 페이지로 이동기능
- 스크랩
- 조회수
- ~추천(로그인한 사용자만)~
- 제보(정보가 이상할시)
- 해당 공지사항을 공유(공지사항을 링크형태 혹은 SNS로 공유할 수 있음)

### 공지사항 관리(관리자 페이지)

- 공지사항 확인/등록/수정/삭제
- 등록 예약
- 학생회별 아이디를 발급

## 식단

- 날짜 선택
- 기숙사 식단/ 학식 확인
- 오늘은 나가서먹자!(지도→식당 카테고리 이동)

## 캘린더

- 날짜선택
- 캘린더에 일정 표시(색 구분)
- 공휴일 표시
- 타임라인
- 타임라인에 대한 알림 설정(선택)

## 지도

- 학교 주변 건물을 맵으로 볼 수 있음(네이버 지도)
    - (학교 건물 / 식당 / 카페 / 그외 유용한 장소[인쇄기 위치, 붕어빵집])
    - 핀 클릭시에 요약정보 카드
- 장소들을 목록화
    - 요약정보 카드 리스트
- 장소 정보
    - 설명, 전화번호, 카테고리, 메뉴
- 정보만 표시, 평가 x
- 사용자 제보

## 더보기

- 내정보
- 서비스 소개 및 팀 소개
- 버전 정보
- 신 기능 랩실
- 밤낮모드 시간설정 / 테마 변경
- 문의/제안

## 추후 확장 가능성

- 타 학교 지원
- UGC(User generated content)
    - 게시판
    - 댓글

**Comment by nohgijin** [comment]
제스~ 로그인 기능 빠지게 된 걸로 결정났으니, 기획서 업데이트 해주실 수 있나요?!

**Comment by jaryapp** [comment]
> 제스~ 로그인 기능 빠지게 된 걸로 결정났으니, 기획서 업데이트 해주실 수 있나요?!

넵 수정할게요~

**Comment by jaryapp** [comment]
충림이 wiki에서 관리합니다
