### ISSUE TITLE
[QA] 홈 디자인 QA

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#930]
- [x] -홈화면 카드, 새로고침 버튼 간 간격 24px로 일정하게, 현재 카드와 새로고침 간 세로간격이 너무 넓음

- [x] - 식단, 공지사항 카드 제목은 medium/header3 으로 맞추기 (간혹 글씨 크기가 커지거나, font weight가 안맞는 경우가 있습니다)

- [x] -식단카드 수정 아이콘 크게

- [x] -식단카드 시간표기는 regular/body 1로 수정

- [x] -푸터 디자인 캠퍼스맵 빠진 버전으로 수정 (스타일가이드 참고)

- [x] -공지사항 선택된 글씨는 medium/body1로 표시, 현재는 regular body1로 표시됨

**Comment by thdwlsgus0** [comment]
이거 제가 작업할게요~!
