### ISSUE TITLE
[QA] 홈화면 식단카드 눌렀을 때 식단으로 링크되는 기능 제안

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#931]
홈 화면에서 식단 카드를 눌렀을 때 해당 식단으로 이동하는 기능을 제안합니다.

예) 홈 개성재 식단 카드 눌렀을 때 -> 식단 페이지 개성재 식단으로 링크됨

**Comment by jaryapp** [comment]
1. 카드 영역 전체 눌렀을때 해당 오늘 식당 페이지로 이동
2. 식당 변경 아이콘 stopPropagation 적용

**Comment by thdwlsgus0** [comment]
@kingyong9169 
혹시 이거 작업중이신가요??

**Comment by kingyong9169** [comment]
> @kingyong9169 혹시 이거 작업중이신가요??

아직 안하고 있습니다! 관심 있으시면 작업 가져가셔도 좋습니다.

**Comment by nohgijin** [comment]
어사인 하셨는데 안하셔서 제가 가져가겠습니다 ~ @thdwlsgus0
