### ISSUE TITLE
[mobile] svg component를 svg 파일형태로 관리

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#933]
## 👩‍💻 기능 설명

현재는 다음처럼 svg를 tsx component로 관리하고있는데, svg는 svg 파일형태로 관리하고 이를 wrapping 할 컴포넌트를 따로 구현하여 className과 style을 적용하도록 변경
https://github.com/CMI-OSS/cbnu-alrami/blob/45bf89f3ebc4b2fd50522dc19479278c7ec29e4f/packages/mobile/src/components/atoms/icon/Map.tsx#L1-L30

### ✅ 참고 사항

- 추가적인 공유가 필요한 사항은 Comment

**Comment by kingyong9169** [comment]
혹시 변경하시는 이유를 알 수 있을까요???

**Comment by jaryapp** [comment]
@kingyong9169
svg 파일 형태가 관리가 편하고 github or vscode에서 preview로 미리 확인할 수 있어서요~

**Comment by kingyong9169** [comment]
preview가 가능하군여! 
제가 가진 의문점은
1. 대규모 리팩토링을 해야 하는데 여기에 시간을 쓸 만큼 이득이 있는지 잘 모르겠어요.
2. 파일 형태로 관리하면 svg 스타일링을 위해 마크업을 확인할 수 있는지? 확신이 없어요.(볼 수 있네요!)

생각되는 장점
1. 기존에는 Setting, Like 등등 아이콘 컴포넌트들을 일일이 만들었던 반면 래핑하는 컴포넌트에 prop으로 통일하여 사용하기 편리함.

결론
나중을 위하면 좋은 것 같아요! 작업 우선 순위를 정하면 좋을 것 같습니다!

정도?? 생각이 듭니다!

**Comment by jaryapp** [comment]
@kingyong9169 
미리보기가 가능해지면 아이콘을 바꾸거나 추가할때 편리할것 같구여, 지금 당장 해야할일은 아니며 조금씩 바꿔나가도 됩니다~
매몰비용 및 앞으로 추가될 아이콘을 생각하면 아이콘 관리는 이렇게 하는것이 더 맞다고 판단되네요~

**Comment by thdwlsgus0** [comment]
좋은 것 같은데요~
이 작업도 리팩토링할 때 같이 하면 좋겠네요~
`next.js`로 변경되는 시점에서 같이 작업하면 좋을 것 같아요!

### 우선순위
1. next.js 마이그레이션
2. svg로 변환 

개인적인 생각으론 스토리북에 사용하고 있는 svg을 나열한 후에 관련 사용처도 같이 명시(mdx 파일)하면 작업할 때 애로사항이 적을 것 같아서 제안드립니다.
