### ISSUE TITLE
[QA] 충림이 공지사항 구독/알림 설정 Flow 누락

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#947]
## 📍 재현 위치

홈 > 설정 > 충림이

![image](https://github.com/CMI-OSS/cbnu-alrami/assets/49256790/36c91bad-55a2-4a64-861d-868143600625)

### 원인
구독 알림 설정 flow가 drawer 컴포넌트로 변경되고 공지사항 목록 페이지에서 구독/알림이 사라지게되면서 `충림이` 공지사항을 구독/알림 설정 할 수 있는 flow가 없어져버렸습니다.

### 제안
충림이를 눌렀을때 drawer 컴포넌트가 나타나야할것 같아요

**Comment by jaryapp** [comment]
@nohgijin @Phlox09022 
확인 부탁드려용~

**Comment by Phlox09022** [comment]
충림이 공지사항은 모두에게 전달되어야하니까, 따로 구독 flow를 만들기보다는 기본적으로 구독 설정이 되도록하면 어떨까요?
그리고 충림이 공지사항은 다른 공지사항보다 눈에 띌 수 있도록 아래 사진과 같이 공지 카드를 만들면 어떨지 제안합니다. 
![충림이 알림](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/127cd6f8-e195-4f81-80a4-604dbff3dd2d)

**Comment by jaryapp** [comment]
@Phlox09022
아이콘 넣은거 귀엽네여 ㅎㅎ 단, 예외는 관리비용을 높이기 때문에 조금 신중할 필요는 있습니다 @nohgijin 확인부탁드려엽

플록스가 말씀하시는건 구독+알림을 기본으로 하자는 거죵?

**Comment by Phlox09022** [comment]
네! 맞습니다

**Comment by jaryapp** [comment]
@Phlox09022
구독+알림을 기본설정으로 하는것까지는 좋은데, 구독과 알림 설정을 해제하게되면 영구적으로 다시 설정할 수 없게되게버려서
이 flow에대한 대응도 필요할것 같네영

**Comment by jaryapp** [comment]
우선, drawer 컴포넌트가 이미 있으니 이를 활용하고 추가 개선해보는게 어떨까 합니다~

**Comment by nohgijin** [comment]
충림이 공지사항 일 경우 미리보기 페이지 오른쪽 상단부에 설정 아이콘을 넣는 방식은 어떨까요~?

**Comment by Phlox09022** [comment]
앗 제 의견은 구독/알림은 기본 설정으로 넣고, 사용자가 설정하지 못하도록 하는 것이었어요!

**Comment by nohgijin** [comment]
전 충림이 게시판에 대한 구독 알림 설정은 들어가야 좋을 것 같아요 ㅎ 그리구 말씀주신 브레드크럼브 관련해서 커스텀 가능합니닷

**Comment by jaryapp** [comment]
저도 설정 들어가는게 좋을듯염

**Comment by jaryapp** [comment]
공지사항 목록 페이지에서 상단 우측에 구독/알림 설정 drawer 열수 있도록

**Comment by Phlox09022** [comment]
![공지사항 보기](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/89737ae2-de50-4e2e-9916-d431fd4ca659)


피그마에 디자인 제작했습니다! 확인해주세요~
https://www.figma.com/file/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?type=design&node-id=953-1153&mode=design&t=fG0Lf1NiJ7J36R9S-0

@jaryapp @nohgijin

**Comment by Phlox09022** [comment]
공지사항 보기 디자인 수정 (미리보기 페이지인데 메인화면처럼 푸터, 태그 들어간 것 수정)
