### ISSUE TITLE
[QA] 안드로이드 앱 아이콘 비율 문제

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#954]
## 📍 재현 위치

안드로이드

## 📌 상황 설명

안드로이드 앱에서 앱아이콘 여백이 너무 좁습니다. 사진의 After처럼 보일 수 있도록 수정 부탁드립니다.

### ✅ 참고

![Frame 581 (1)](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/42145ceb-c957-4e4f-82bb-1f7e33ec10ed)

**Comment by jaryapp** [comment]
@Phlox09022 
수정했습니당
![image](https://github.com/CMI-OSS/cbnu-alrami/assets/49256790/f4c3b136-c3bd-4fed-8a13-0e02de5397f0)

바꾸는김에 스플래시 이미지도 바꿨어영
![image](https://github.com/CMI-OSS/cbnu-alrami/assets/49256790/116fd957-2eba-49c4-aef1-25eb4bf2dea8)
