### ISSUE TITLE
[QA] 식단 QA 2차

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#956]
## 📍 재현 위치
식단

## 📌 상황 설명

- [x] 선택된 부분 폰트 medium/body1로 수정

- [x] 식단카드 제목, 시간 중앙정렬 맞추기

- [x]  시간 폰트 regular / body1로 수정

- [x]  식단카드 본문 폰트 regular / body1로 수정

### ✅ 참고

![식단](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/85581d08-2d8e-440a-ac2b-327507200728)

**Comment by thdwlsgus0** [comment]
이거 작업해둘게요~
