### ISSUE TITLE
[admin] redux toolkit reducer 관련 에러

### ISSUE THREAD

**Issue by thdwlsgus0** [CMI-OSS/cbnu-alrami#96]
## 📌 문제 상황
초기 화면부터 `reducer` 관련 에러가 발생합니다.

## 🐛 발생 위치
`admin` 패키지에서 `ScraperPage` 컴포넌트 

### ✅ 참고 스크린 샷
<img width="1052" alt="스크린샷 2022-01-11 오후 11 07 40" src="https://user-images.githubusercontent.com/22065725/148957769-76c52638-5426-449e-bed0-9ed1f984c729.png">

**Comment by kingyong9169** [comment]
App.tsx에서 Provider 부분 주석 처리했더니 에러 사라져요!  reducer가 없어서 저런 오류가 발생한 것 같습니다!

**Comment by thdwlsgus0** [comment]
Provider 로직을 구현하면 저절로 해결되겠네요 ㅎㅎ 저 부분은 상태관리 좀 더 추가할 때 작업하면 될 것 같습니당
