### ISSUE TITLE
[QA] 모달 디자인 수정

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#962]
## 📍 재현 위치

전체

## 📌 상황 설명

- [x] 기본 모달 디자인 2개 수정
- [x] 식단 모달 디자인 수정 
(식단 모달은 버튼 디자인 제외하면 이전 디자인과 동일합니다.)

### ✅ 참고
![모달](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/c98b255a-e5b5-4a25-8b8e-c917c64fa25d)
기본 모달: https://www.figma.com/file/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?type=design&node-id=0-1&mode=design&t=fG0Lf1NiJ7J36R9S-0

![식단](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/5bf910c8-cc81-4fff-8c7e-82680911cae3)
식단 모달: https://www.figma.com/file/fCzuV7VJDKWY9N6J89XKV0/%EC%B6%A9%EB%A6%BC%EC%9D%B4?type=design&node-id=901-41&mode=design&t=fG0Lf1NiJ7J36R9S-0

**Comment by thdwlsgus0** [comment]
이것도 제가 할게요~

**Comment by thdwlsgus0** [comment]
@Phlox09022 
기본 모달 변경된 부분이요~
혹시 버튼만 변경된걸로 이해하면 될까요?

**Comment by Phlox09022** [comment]
@thdwlsgus0 
네 맞습니당
