### ISSUE TITLE
[QA] 충림이 앱 최초 실행 시 식단 안뜸

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#971]
## 📍 재현 위치

홈화면

## 📌 상황 설명

충림이 앱 최초 실행 시 식단을 선택해주세요가 떠야하는데, 창이 뜨지 않고 날씨와 공지사항만 뜹니다.
그러나 다른 화면(공지, 식단, 일정 등)을 왔다갔다한 뒤 홈으로 되돌아오면 식단을 선택하는 카드가 떠있습니다.

**Comment by thdwlsgus0** [comment]
이거 혹시 사용하시는 디바이스랑 스크린샷 정도로 남겨주실 수 있나요?
어떤 문제인지 파악하기에 좀 더 용이할 것 같습니다.

**Comment by Phlox09022** [comment]
갤럭시 s8입니다!![Screenshot_20230821-003712.jpg](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/f001fa1e-6074-44c8-acee-4300db5b8899)

**Comment by Phlox09022** [comment]
> 갤럭시 s8입니다!
![Screenshot_20230821-003712.jpg](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/f001fa1e-6074-44c8-acee-4300db5b8899)
> 
>

**Comment by jaryapp** [comment]
@Phlox09022 @thdwlsgus0 
https://github.com/CMI-OSS/cbnu-alrami/blob/55ec398315d952765e86b23300cfd8d4dc79c37b%5E/packages/mobile/src/page/Home/Restaurant/hooks.ts#L68
이부분이 문제여서 수정했습니다~ 배포까지 완료됐어요
웹에서는 localStorage 초기화하거나 앱에서는 삭제후 재설치하면 미재현 확인 가능할거에요~

**Comment by thdwlsgus0** [comment]
확인됐으면 이 이슈는 닫아도 될 것 같아요~
