### ISSUE TITLE
[QA] 설정>만든이 삭제 제안

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#972]
## 📍 재현 위치

설정>만든이

## 📌 상황 설명

현재 만든이 페이지는 미완성 된 상태입니다.
하지만 만든이 페이지를 만드려하니 탈퇴하신 분들 닉네임도 작성해야할 지, 디자인은 어떻게해야 할 지 등의 고민으로 인해 만들지 못하고있습니다.
만든이 페이지에 대한 아이디어가 있다면 의견 남겨주시고, 만약 의견이 없다면 삭제 후 아이디어가 나오면 그 때 다시 추가하는 것이 좋을 것 같습니다.

**Comment by thdwlsgus0** [comment]
그래도 만든이 페이지는 기여하신분들 다 들어가면 좋긴한데 
실명을 언급하는 것보단 닉네임으로 가는게 더 좋을 것 같아요!
탈퇴하신분들 중에 연락이 닿으시는 분들 위주로 여쭤보고 넣을지 말지 결정하면 될 것 같아요

**Comment by jaryapp** [comment]
https://www.dev-mobile.cmiteam.kr/setting/creator
저는 현재 팀이름 + 로고도 괜찮은것 같습니다.
그리고 나중에 팀소개 사이트를 만들어서 여기로 랜딩하면 어떨까해염
