### ISSUE TITLE
[QA] 충림이 앱 아이콘 2차 수정

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#973]
## 📍 재현 위치

앱 아이콘

## 📌 상황 설명

현재 충림이 앱 아이콘의 여백이 너무 넓은 관계로 다시 수정합니다.  사진과 앱 아이콘 첨부파일을 참고하여 재수정 부탁드립니다.

![화면](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/5e2b38c6-db12-489d-91ba-5fa367d7a5ce)
<안드로이드 화면>

![화면_아이폰](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/ca8f32c5-2108-47a4-a786-3389f17d67bb)
<아이폰 화면>

### ✅ 참고
<앱 아이콘 첨부파일>
파일을 다운로드 받은 후, 필요한 기종에 맞춰 사용해주세요
[IconKitchen-Output.zip](https://github.com/CMI-OSS/cbnu-alrami/files/12425213/IconKitchen-Output.zip)

**Comment by thdwlsgus0** [comment]
요거 급한건가요?

**Comment by Phlox09022** [comment]
아이콘 가시성 문제 때문에 8/31 전까지는 꼭 수정해주셨으면 합니다

**Comment by jaryapp** [comment]
수정완료
