### ISSUE TITLE
[QA] 공지사항 x 버튼 경로 수정

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#978]
## 📍 재현 위치

공지사항>구독/알림, 구독페이지

## 📌 상황 설명

![Frame 622](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/1528afaf-198e-4ad2-a558-dd7ddd784a53)

**Comment by jaryapp** [comment]
수정완료
