### ISSUE TITLE
[QA] 공지사항 미리보기 아이콘 색상 문제

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#979]
## 📍 재현 위치

공지사항 미리보기

## 📌 상황 설명

![Frame 623](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/8e925173-798d-46fc-b10d-c5f2a6328132)

**Comment by thdwlsgus0** [comment]
이것도 제가 수정할게요~
