### ISSUE TITLE
[설계] 충림이v2 ERD

### ISSUE THREAD

**Issue by jaryapp** [CMI-OSS/cbnu-alrami#98]
### 개요
- [충림이v2 기획](https://github.com/CMI-OSS/cbnu-alrami/issues/93)을 기반으로 ERD를 설계합니다
- RDB를 기준으로 테이블을 설계합니다

### Diagram
https://dbdiagram.io/d/61e5661450665b3304397c8f

### Rule
- Field명은 camelCase

질문, 제안, 의견 해당 이슈에 코멘트 부탁드립니다~

**Comment by EunjiShin** [comment]
https://app.quickdatabasediagrams.com/#/d/YNgM31

**Comment by JeongHyeongKim** [comment]
설계도를 회사에 두고 왔군요

오늘 내일 중으로 했던거 기억해서 올려놓겠습니다.

**Comment by jaryapp** [comment]
#### 22.01.22(토) 백엔드 10:00 ~ 12:00 ERD 설계 1차 회의  with @CMI-OSS/cbnu_alrami_be 
- admin 계정에 role 부여 (스크래퍼(notice 권한), CMI팀(모든 권한), 학생회(학생회 게시판 관리), 뷰어(일부 게시판 조회만))
- admin계정과 관리할 사이트와의 연관 관계(read, write 권한 등)
- Site 테이블에 학생회를 포함할 수 있는 개념 확장
- Scrap에 pk 혹은 날짜 부여 => 사용자가 최근 등록한 순서로 보기 편하도록
- 휴먼 사용자 일부 데이터 삭제 정책
- 구독 후에만 알림설정 가능하도록
- MySQL vs PostgreSQL (https://techblog.woowahan.com/6550/)
- 각자 https://dbdiagram.io/home 로 작업후 설계 => 통합후 하나의 ERD에서 협업 가능하도록 프리미엄 결제 예정
- Place 테이블 신설(좌표 이름 전화번호 주소 등) - 지도에 표시될 데이터
- redis에 관리할 데이터 구분(외부 api 호출, 굳이 DB에 저장할 필요 없는 일시적인 데이터 등)
- 그밖에 관리자페이지에서 필요할것 같은 데이터 (사용자 추가된 날짜, 게시물 추가된날짜, 업데이트 날짜 등)
- 게시물 추천 기능 제거
- NoSQL에서 관리할 데이터 분리( 사용자 로그, 스크래퍼 로그 등)

**Comment by EunjiShin** [comment]
- 저희 RDBMS + Redis로 두 가지 사용하는건 아직 픽스된게 아니라 검토 단계인거죠? 👀
- 회의 중 **공지사항을 스크랩한 수 (몇명이 이 공지사항을 스크랩했는지)** 를 게시물 추천 기능에 활용하자는 의견이 있었던 것 같은데, 게시물 추천 기능 제거라고 기재되어 있네요! 아래 내용으로 이해하고 있는데 맞는지 확인 부탁드립니다. 
  - 비회원 기능으로 확정되면서 게시글 추천 기능 제거
  - 게시글 추천 수로 구현되던 게시물 추천 기능을 스크랩 수 기반으로 변경

**Comment by EunjiShin** [comment]
(제안)
만약 Redis와 RDBMS를 병행할 예정이라면, CQRS패턴을 도입해보는 건 어떨까요? 
Creat/Update/Delete 중심 기능과 Read 중심 기능을 분리하는 패턴인데, 최근 관심가지고 있는 분야라 공유드립니다. 
https://www.youtube.com/watch?v=fg5xbs59Lro 
https://github.com/nestjs/cqrs

**Comment by jaryapp** [comment]
@EunjiShin 
> 저희 RDBMS + Redis로 두 가지 사용하는건 아직 픽스된게 아니라 검토 단계인거죠? 👀

네네 확정된건 아니고 그때 Redis 얘기가 나와서 넣어봤습니다
Redis를 적용할것인지도 논의해보면 좋겠군여

> 회의 중 공지사항을 스크랩한 수 (몇명이 이 공지사항을 스크랩했는지) 를 게시물 추천 기능에 활용하자는 의견이 있었던 것 같은데, 게시물 추천 기능 제거라고 기재되어 있네요! 아래 내용으로 이해하고 있는데 맞는지 확인 부탁드립니다.

아하 정확히는 게시물 추천을 통해서 인기 게시물을 추출하려고 했는데 비회원으로 확정되고 사용자들이 추천을 잘 누를것 같지 않아서 게시물 추천 기능은 제외하돼 인기 게시물 추출을 스크랩 수를 통해서 하려고 합니다.

CQRS패턴은 제가 잘 몰라서 적어주신 자료를 확인해보겠습니다!
이에 대해 @JeongHyeongKim 조나슨과 다른 백엔드분들의 의견이 궁금합니다 cc. @CMI-OSS/cbnu_alrami_be

**Comment by JeongHyeongKim** [comment]
cqrs 한번 사용해보시죠ㅎㅎ

저도 redis는 단순 제안입니다. 여러분이 동의하거나 쓰고싶다면 도입을 하는쪽으로 하고 싶습니다.

**Comment by JeongHyeongKim** [comment]
스크랩수로 추적하는 부분 동의합니다.

**Comment by JeongHyeongKim** [comment]
https://dbdiagram.io/d/61eff4527cf3fc0e7c63ccc2

**Comment by EunjiShin** [comment]
https://dbdiagram.io/d/61f5d94d85022f4ee5103146

업데이트 버전

**Comment by EunjiShin** [comment]
// fk = null 일때 cascade 옵션에 대한 예외 핸들링 필요 
// null 이 많은 경우 -> 사용X 컬럼일 가능성 -> 분리 필요 

// user - admin 분리 (adminSite 접속 필요)
// admin은 login 필요 -> id, pw

// 북마크 테이블 필요 

// 권한별 가능 메뉴 
// 소속별 권한 추가로 필요 ! 
// Ex, A학생회가 B 학생회 글에 접근 못하게 

// 일반 학생의 소속 -> 관리 용도 필요 
// 일반 학생과 학생회 테이블 분리하면 신경쓸 필요 X

// Covid, Weather은 Redis (key-value)로 따로 봐야함

**Comment by EunjiShin** [comment]
site 소속을 관리하는 트리 구조 필요 
(Ex. 어느 학생회가 어느 단과대에 소속되어 있는지 등)

**Comment by EunjiShin** [comment]
- 조회수 이슈
1. get 요청 : 새로고침할 때마다 중복
2. session 이용 : 만료될 때마다 중복 (고려 필요)
3. DB저장 : 현재 best. 프론트에서 특정 사용자가 읽은 공지사항 / 안읽은 공지사항 구별해줄 때도 활용 가능

**Comment by EunjiShin** [comment]
북마크에 저장된 공지사항은 조회 중복 허용을 해 줄것인가?

**Comment by EunjiShin** [comment]
외부 식당의 메뉴는 json으로 저장 or 메뉴 테이블 분리

**Comment by EunjiShin** [comment]
> 외부 식당의 메뉴는 json으로 저장 or 메뉴 테이블 분리

- json 저장 예시
https://www.lesstif.com/dbms/mysql-json-data-54952420.html

- 메뉴 테이블 분리 방식 예시 
![IMG_B0A26746E7FB-1](https://user-images.githubusercontent.com/38103085/152137396-e0936fe2-e415-4db6-abd7-7a40caf8d850.jpeg)

**Comment by EunjiShin** [comment]
- 중복 체크하는 방식 @CMI-OSS/cbnu_alrami_be 
공지사항, 메뉴 등 스크래핑해올 때 중복체크 필요! 

1. 여러 컬럼에 pk를 지정 
(Ex. date, time에 각각 pk를 걸어서 date+time으로 유니크한지 확인)
: DB단에서 중복체크 가능 

2. pk는 id (Auto Increment)에만 걸고, 중복체크는 컬럼을 조회해서 
(Ex. request의 date, time을 DB에서 조회해서 -> 있다면 중복, 없다면 insert)
: 코드단에서 중복체크 가능

**Comment by EunjiShin** [comment]
- nest.js에서도 @Transcation 어노테이션 등의 트랜잭션 지정해 줄 수 있는 방식이 있는지 확인할 것!

**Comment by EunjiShin** [comment]
- 테이블에서 crated_at, updated_at을 가지는 방식 @CMI-OSS/cbnu_alrami_be 
1. 모든 테이블이 공통으로 가지도록 한다
2. 필요한 테이블과 필요하지 않은 테이블을 구분한다 (->필요한 친구들 리스트업 및 내부 협의 필요)

**Comment by EunjiShin** [comment]
https://dbdiagram.io/d/61ff148785022f4ee544cece

**Comment by sween2591** [comment]
https://dbdiagram.io/d/61f5d05385022f4ee5101e38

**Comment by jaryapp** [comment]
충림이 wiki에서 관리합니다
