### ISSUE TITLE
[QA] 일정 작동방식 수정

### ISSUE THREAD

**Issue by Phlox09022** [CMI-OSS/cbnu-alrami#995]
## 📍 재현 위치

홈화면-일정
일정-즐겨찾기

## 📌 상황 설명

"추석" 일정을 즐겨찾기해두었는데
11월인 지금, 아직도 홈화면에 추석이 떠있습니다.

홈화면에는 즐겨찾기 했으면서 오늘에 해당하는 일정만 뜨도록,
즐겨찾기에는 해당 월에 즐겨찾기 한 일정만 뜨도록 수정 부탁드립니다.

### ✅ 참고
![Frame 613](https://github.com/CMI-OSS/cbnu-alrami/assets/100134173/c3279db5-0590-4dcb-b54b-13c16dc2d8f5)

**Comment by jaryapp** [comment]
@Phlox09022 이슈 해결해서 배포까지 완료했습니다~
